### ISSUE TITLE
buffer.js, `this` is not defined with ignition/turbo options

### ISSUE THREAD

**Issue by dvlsg** [zeit/pkg#101]
Odd one here. Trying to make the suggestion [here](https://github.com/zeit/pkg/issues/55#issuecomment-298785574) work with my codebase.

Here's the literal error output from the codebase I'm trying to pkg:
```
buffer.js:12
    super(arg1, arg2, arg3);
    ^

ReferenceError: this is not defined
    at FastBuffer (buffer.js:12:5)
    at fromString (buffer.js:212:11)
    at Function.Buffer.from (buffer.js:105:12)
    at new Buffer (buffer.js:86:17)
    at evalmachine.<anonymous>:0:0
    at readPayload (_pkg_bootstrap.js:34:10)
    at _pkg_bootstrap.js:38:11
    at _pkg_bootstrap.js:46:2
    at NativeModule.compile (bootstrap_node.js:529:7)
    at Function.NativeModule.require (bootstrap_node.js:470:18)
```

I can't quite figure out where this is happening inside my codebase, but I have an example which reproduces a very similar (if not the same) error. At least it's the same `this is not defined` coming from `buffer.js:12`. 

* Target: `node7-win-x64`
* Options:
  * ignition
  * turbo
  * turbo-from-bytecode

Here's a code example, followed by some explanation:

```js
const crypto = require('crypto');
const iterations = 10000;
for (let i = 0; i < iterations; i++) {
  crypto.createCipher('aes-256-ctr', 'somenonsensepassword');
}

```

To make the error occur:
* I have to compile with *all* of `ignition`, `turbo`, and `turbo-from-bytecode`.
  * Seems to work fine if I leave all (or some, oddly enough) of the options off.
* For some reason, the iterations matter in this example. If I drop it down to say, `1000`, the error does not occur

I don't have large numbers of iterations anywhere in my codebase like this (at least not that I'm aware of, could be in a node module somewhere I suppose). I sort of stumbled across this one by accident while trying to do some performance comparisons locally, moved on to see if I could even package my own application once I hit the error, and happened to receive the same error.

**Comment by dvlsg** [comment]
Oh I just saw [this](https://github.com/zeit/pkg/issues/55#issuecomment-299552789) too, and the following [comment](https://github.com/zeit/pkg/issues/55#issuecomment-299597995). I'll just close this for now, then.

**Comment by igorklopov** [comment]
Let's keep it open for a while. Probably i will find time to look into the issue.

**Comment by igorklopov** [comment]
Please check again with `pkg@4`. Ignition/TurboFan seems more mature there.
