### ISSUE TITLE
adding icon or information to compiled exe causes exe to stop working

### ISSUE THREAD

**Issue by serkanp** [zeit/pkg#105]
when i add icon and version information using resource hacker , when you run the app, command prompt of node appears and app is no longer working.

**Comment by igorklopov** [comment]
Hi Serkan! Is it similar to https://github.com/zeit/pkg/issues/91 ?

**Comment by serkanp** [comment]
yes it is same.. 
as you knowi on enclosejs it was easy to add it with resource hacker. now pkg does not allow to add information to compiled exe.

**Comment by igorklopov** [comment]
Ok. Lets chat there. https://github.com/zeit/pkg/issues/91
