### ISSUE TITLE
Usage with NodeJS Server

### ISSUE THREAD

**Issue by harshalyeole-tudip** [zeit/pkg#106]
Please help me with the steps to intregate this with node webapp.

I'm getting this error when I use **pkg .**
:Error! Property 'bin' does not exist in /home/lt-101/16may/package.json

**Comment by igorklopov** [comment]
Add `bin` property to your `package.json` and make it's value point to your starting javascript file.

**Comment by harshalyeole-tudip** [comment]
It worked and created following files

- 16may-linux
- 16may-win.exe
- server-linux​
- server-win.exe

How do I run it?

**Comment by harshalyeole-tudip** [comment]
**16may-win.exe** was executed on windows and worked fine.

Then a question again what is the use of  **server-win.exe** file


LINUX executing is still indark I dont know how to use it.

**Comment by igorklopov** [comment]
Please erase all 4 files and try running pkg again. I am sure it creates only `16may-linux` and `16may-win.exe`.
