### ISSUE TITLE
Warnings in gulp-cli and matchdep

### ISSUE THREAD

**Issue by ogranada-xk** [zeit/pkg#110]
Building a simple package a got the next warnings:
```bash
> pkg@3.0.4
> Targets not specified. Assuming:
  node6-linux-x64, node6-macos-x64, node6-win-x64
> Warning Cannot resolve 'path.join(__dirname, '/lib/versioned/', range, '/')'
  /Users/Oscar/git/poc_bin/node_modules/gulp-cli/index.js
  Use a string literal as argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
> Warning Cannot resolve 'pkgPath'
  /Users/Oscar/git/poc_bin/node_modules/gulp-cli/index.js
  Use a string literal as argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
> Warning Cannot resolve 'resolve(config, { basedir: callerPath })'
  /Users/Oscar/git/poc_bin/node_modules/matchdep/lib/matchdep.js
  Use a string literal as argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
> Warning Cannot resolve 'filePath'
  /Users/Oscar/git/poc_bin/node_modules/gulp-cli/lib/shared/config/load-files.js
  Use a string literal as argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
```
Any idea?

Thanks.

**Comment by ogranada-xk** [comment]
The issue is because gulp use a bunch of require statements using variables (I have gulp installed in my project), so when the project processed by `pkg` the warnings are launched.

**Comment by igorklopov** [comment]
How it happens that `require('gulp')` gets in your production code?

**Comment by ogranada-xk** [comment]
Not exactly, if you have installed the library in your node_modules happens even if you don't use gulp in your code.

**Comment by igorklopov** [comment]
`gulp` can get into production code only if you install it into `dependencies`. Please be sure to install it into `devDependencies`.

**Comment by ogranada-xk** [comment]
I'm developing a tool that use gulp directly, that is the reason to have gulp in production.

**Comment by igorklopov** [comment]
Please look how gulp should be compiled with pkg:
https://github.com/zeit/pkg/blob/master/test/test-79-npm/gulp/gulp.js
