### ISSUE TITLE
Change icon and other details for an executable

### ISSUE THREAD

**Issue by sharathbaddam** [zeit/pkg#112]
Hello,

This is just a question.

I was using nexe for a while now and I was able to change the icon and other application details in nexe.
Is there any way to change those details using pkg ?

Any help is really appreciated.

-Sharath

**Comment by igorklopov** [comment]
Hi. It is a known bug, but there is a temporary workaround.
https://github.com/zeit/pkg/issues/91#issuecomment-302853037
