### ISSUE TITLE
Nodejs Prompt when run from a different directory

### ISSUE THREAD

**Issue by glennswest** [zeit/pkg#113]
I package the executable, but it seems to not find it self when I move the executable.

Source: https://github.com/glennswest/mcinit

Running transaction
  Updating   : mcinit-rpm-1.0-4.x86_64                                                                                                            1/2 
  Cleanup    : mcinit-rpm-1.0-3.x86_64                                                                                                            2/2 
  Verifying  : mcinit-rpm-1.0-4.x86_64                                                                                                            1/2 
  Verifying  : mcinit-rpm-1.0-3.x86_64                                                                                                            2/2 

Updated:
  mcinit-rpm.x86_64 0:1.0-4                                                                                                                           

Complete!
[root@dev mcinit]# cd ..
[root@dev ~]# mcinit
> 
(To exit, press ^C again or type .exit)
> 
[root@dev ~]# ^C
[root@dev ~]# mcinit/mcinit
mcinit: Starting
Adding Key
Adding Key
[root@dev ~]#

**Comment by igorklopov** [comment]
Sorry, too time consuming to run your entire project. Please provide a minimal project that reproduces the problem.
