### ISSUE TITLE
Obfuscated JS - Require needs string

### ISSUE THREAD

**Issue by Webrow** [zeit/pkg#114]
This might be bad knowledge form my side but ill try and explain it as good as I can. 
Im working on a obfuscated project, and trying to build the nodeapp for a RPi3.  

Whenever I am running pkg I get the warnings regarding the require's. 
` Warning Cannot resolve '_0xc23f('0x0')'
  /home/pi/gb/index.js
  Use a string literal as argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
`  
Which is this line: const util = require(_0xc23f('0x0'));
Now I do have the deobfuscated code for this part since knowing the imports doesnt endanger the project. Below are two lists:   
```
const fs = require('fs');
const util = require('util');
const _ = require('lodash');
const colors = require('colors');
const path = require('path');
const math = require('mathjs');
const sprintf = require('sprintf-js').sprintf;
const request = require('request');
const readLastLines = require('read-last-lines');
let http = require('http');  
let Promise = require('bluebird');  
let lib = require('./lib.js');  
let a= require('./a.js');  
let b= require('./b.js');  
let c= require('./c.js');  
```

which corresponds with:  
```
const fs = require('\x66\x73');
const util = require(_0xc23f('0x0'));
const _ = require(_0xc23f('0x1'));
const colors = require(_0xc23f('0x2'));
const path = require(_0xc23f('0x3'));
const math = require(_0xc23f('0x4'));
const sprintf = require('\x73\x70\x72\x69\x6e\x74\x66\x2d\x6a\x73')[_0xc23f('0x5')];
const request = require('\x72\x65\x71\x75\x65\x73\x74');
const readLastLines = require(_0xc23f('0x6'));
let http = require('\x68\x74\x74\x70');
let Promise = require(_0xc23f('0x7'));
let lib = require(_0xc23f('0x8'));
let a= require(_0xc23f('0x9'));
let b= require(_0xc23f('0xa'));
let c= require(_0xc23f('0xb'));
```

I have no idea how to solve this issue. neither do I understand why some of them are string literals, and some of them aint.

**Comment by igorklopov** [comment]
Ok. Aside warnings, what issues do you have when you run such application as compiled executable?

**Comment by Webrow** [comment]
Running nodejs index.js waits a couple of seconds and puts out :"No pairs selected" ( thats an printed message from the tool).  

after running: `pkg -t armv7 index.js` I see the warnings. Next I run ./index this takes a looooong time. and then :  

``pi@raspberrypi:~/gb` $ ./index

<--- Last few GCs --->

[17381:0x35604f8]   249934 ms: Mark-sweep 817.7 (858.0) -> 817.5 (861.5) MB, 4679.2 / 0.0 ms  allocation failure GC in old space requested
[17381:0x35604f8]   254590 ms: Mark-sweep 817.5 (861.5) -> 817.4 (862.0) MB, 4654.7 / 0.0 ms  allocation failure GC in old space requested
[17381:0x35604f8]   258423 ms: Mark-sweep 817.4 (862.0) -> 817.4 (847.0) MB, 3817.3 / 0.0 ms  last resort
[17381:0x35604f8]   263040 ms: Mark-sweep 817.4 (847.0) -> 817.4 (847.0) MB, 4617.0 / 0.0 ms  last resort


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x41e16671 <JS Object>
    2: setCookie [evalmachine.<anonymous>:0] [pc=0x4913a2ac](this=0x51bf9199 <an Object with map 0x5142ef21>,_0x37f370=0x51bf9189 <JS Array[9230308]>,_0xe7187d=0x2839a6d1 <String[7]: counter>,_0x782ba0=1,_0x435966=0x51bf916d <an Object with map 0x51404629>)
    3: arguments adaptor frame: 3->4
    4: _0x5baa28 [evalmachine.<anonymous>:0] [pc=0x49139e68](this=0x41e7f015 <JS Global Object>)
    5: /*...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
Aborted
pi@raspberrypi:~/gb $
`

**Comment by igorklopov** [comment]
@Webrow please try again with `pkg@4`
