### ISSUE TITLE
Dynamic file

### ISSUE THREAD

**Issue by Aymkdn** [zeit/pkg#115]
Hi,

I have a configuration file called `config.json`. In my `index.js` I read its content with `require("./config.json")`. This is a dynamic config file that should be updated by the user.

When I use `pkg` this config file is included into the package. As it's a dynamic resource I don't want it to be included into `index.exe`, but I want it to be read by `index.exe` at runtime.

Any idea how I could proceed?

I don't really want the users to type into the command line all the configuration.

Thanks

**Comment by igorklopov** [comment]
You want to read from real file system - use `path.dirname(process.execPath)` or `process.cwd()`. Please refer `readme.md`.
