### ISSUE TITLE
Makeself, pkg and background process.

### ISSUE THREAD

**Issue by roccomuso** [zeit/pkg#118]
I'm trying to use [Makeself](https://github.com/megastep/makeself) to make a self-extracting archive with a pkg-ed node.js script inside (For linux) and compress my package ( #50 ).

This is my archive `bkdr/` content:
- bkdr-linux
- exec.sh

This the command used to build the self-extracting archive (`bkdr.run`) and run the startup script `exec.sh`:

    $ ./makeself.sh bkdr/ bkdr.run "hello world" ./exec.sh

`exec.sh` should simply run my pkg-ed node script in background:

```shell
#!/bin/sh
./bkdr-linux &
```
But here the error pkg is raising: `Pkg: Error opening file.`

Being said that, a direct execution of `exec.sh` works as expected.
And also If I get rid of the `&` everything works (but of course the process is not executed in background).

Any hint?

Could this be somehow related?

> Usage of packaged app
> Command line call to packaged app `./app a b` is equivalent to `node app.js a b`

**Comment by igorklopov** [comment]
`backdoor-linux` :joy: anyway looking on it

**Comment by roccomuso** [comment]
@igorklopov gg, yeah just having some fun with `pkg` :) LMK

**Comment by igorklopov** [comment]
Seems that it is not pkg issue. I think it fails mostly because temporary directory where Makeself unpacks the files is deleted, and `process.cwd()` and `process.execPath` (which pkged binary relies on) fail. You can try the following `exec.sh` even without pkg:
```
#!/bin/sh
node bkdr.js &
```
And `bkdr.js`:
```
console.log(process.execPath);
```
I you pass `--notemp` this will lead to using persistent directory. If you remove `&` this will keep execution inside `exec.sh` before deleting temporary directory.

**Comment by igorklopov** [comment]
Let me close it for now :)

**Comment by roccomuso** [comment]
A new attempt gives me a different error.

This is now the `exec.sh`:

```sh
#!/bin/sh
cp ./bkdr-linux /tmp/
chmod 755 /tmp/bkdr-linux
/tmp/bkdr-linux &
```

And gave my this:

```
Error: ENOENT: no such file or directory, uv_cwd
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
```

**Comment by igorklopov** [comment]
Yeah, you avoided the case when the directory (the executable is placed in) is deleted. But `process.cwd()` still points to that temporary directory that is deleted. Maybe try adding `cd /tmp/` and running the executable like `./bkdr-linux &`

**Comment by roccomuso** [comment]
@igorklopov yeah at the end I've solved with a `cd /tmp`. Thanks.

Here the final `setup.sh`:

```sh
#!/bin/sh
cp ./bkdr-linux /tmp/
chmod 755 /tmp/bkdr-linux
cd /tmp
/tmp/bkdr-linux &
```

**Comment by huynhquocmy** [comment]
Thanks muc @roccomuso , it saved my day 👍
