### ISSUE TITLE
access embedded assets from another process

### ISSUE THREAD

**Issue by ainglese** [zeit/pkg#119]
i'm considering pkg for building a CLI; on our cli we may need to execute some external process passing them a script (suppose invoking a powershell and passing a powershell file) that we want to embed as an asset. Is it possible for the other process (the powershell one in the example) to access assets embedded into the packaged executable?

the alternative for what i see is making the packaged application extract the assets to a temp folder and then execute from there.

**Comment by igorklopov** [comment]
I think you should serve internal assets via http from 0.0.0.0 or using some other IPC.
