### ISSUE TITLE
Trying to run with ES6 and using babel to transcopile. Get the following error...

### ISSUE THREAD

**Issue by HappyZombies** [zeit/pkg#123]
"import and export may appear only with sourcetype: module"

Maybe I didn't read the docs right...or maybe ES6 is just not supported at all....if not it's no biggy, I can change my current project to ES5. (Besides it's mainly import that I am using...)

[express-es6-pkg.zip](https://github.com/zeit/pkg/files/1050955/express-es6-pkg.zip)

Here's a the express example you provide but with babel integrated. Run npm i and then run node index.js and you will see that it works fine. However when I run pkg . it get the error mentioned above. I wasn't too sure where I had to put this...so I am guessing that this on your side not my code side (if it is please tell me where I need to put it . . .) or if you have any idea on how to make it work please do ! Thanks :)

**Comment by boristian** [comment]
Hi,

I'm having the same Problem when trying to pkg an Webapp using [redux](https://github.com/reactjs/redux), which is depending on [lodash-es](https://www.npmjs.com/package/lodash-es).

Is this even possible, ist there any workaround?

Thanks an greets

P.S.: Thanks for the great work and opensourcing it. Having the possibility to generate self-contained node executables is very helpful.

**Comment by rwatts3** [comment]
Also having this issue any suggestions would be great.

**Comment by GitHubWuYi** [comment]
Error! 'import' and 'export' may appear only with 'sourceType: module' (1:0)
I get this problem too,how to fix it ?

**Comment by ayan4m1** [comment]
Windows 10 x64, I am getting the following output:

> pkg@4.1.2
> Targets not specified. Assuming:
  node8-win-x64
> Warning Cannot resolve 'path'
  C:\code\forge-fetch\node_modules\requirefresh\out\lib\requirefresh.js
  Dynamic require may fail at run time, because the requested file
  is unknown at compilation time and not included into executable.
  Use a string literal as an argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
> Error! 'import' and 'export' may appear only with 'sourceType: module' (178:0)
  C:\code\forge-fetch\node_modules\safefs\es6\lib\safefs.js

I have `pkg` installed globally and am running `pkg bin/forge-fetch.js` from the root directory of my project. I have also tried running it programmatically:

> pkg.exec(['bin/forge-fetch.js', '--output', 'forge-fetch.exe'])

My JS code is being compiled by coffeescript and should not need any polyfills/ES6/babel.

**Comment by Metnew** [comment]
Hi, I'm getting a similar error: 
> Error! 'import' and 'export' may appear only with 'sourceType: module' (10:0)
   /Users/metnev/Profile/project/node_modules/lodash-es/lodash.js

Error appears if `lodash` has been used in bundle, for example following code generates an error: 
```js
var lodash = require('lodash-es')
console.log(lodash)
```

Preprocessing with babel (babel-preset-es2015, babel-lodash-plugin, babel-preset-stage-0) doesn't fix this error.

Node: 8.1.4,
Pkg: 4.1.2,
Target: node8-macos-x64

**Comment by Warafux** [comment]
Same issue:

> **Error!** 'import' and 'export' may appear only with 'sourceType: module' (1:0)
  C:\xampp7\htdocs\TraceMapRoute\app\node_modules\acorn\dist\acorn_loose.es.js

Inside acorn_loose.es.js:

```
import { defaultOptions, addLooseExports, SourceLocation, tokTypes, tokenizer, Node, lineBreak, isNewLine, getLineInfo, Token, lineBreakG } from './acorn';

// Registered plugins
var pluginsLoose = {}
////////////////////////////////////////////////

```
My dependencies:
```
  "dependencies": {
	"express": "4.15.2",
    "prompt": "^1.0.0",
    "socket.io-client": "^2.0.3",
    "nodejs-traceroute": "^1.1.1"
  },
```
Node: v6.11.1
Pkg: 4.1.2
Target: node6-win-64

Any help would be greatly appreciated, thanks!

**Comment by igorklopov** [comment]
Please try using pkg 4.1.3. And please FYI, if `node index.js` does not run, then compiled binary will not run too (or will even not compile). Please transpile and point pkg to transpiled output.

**Comment by Metnew** [comment]
Thanks @igorklopov, pkg@4.1.3 fixed this issue for me.
