### ISSUE TITLE
require local file throw cannot find module  

### ISSUE THREAD

**Issue by meiduo** [zeit/pkg#124]
![image](https://cloud.githubusercontent.com/assets/7929293/26774149/6ca565c2-4a01-11e7-8dd5-e36546596e98.png)
![image](https://cloud.githubusercontent.com/assets/7929293/26774153/7426494c-4a01-11e7-8999-e4a213b7328a.png)
![image](https://cloud.githubusercontent.com/assets/7929293/26774136/596d9312-4a01-11e7-9347-53b38c45404e.png)

And I use  **pkg -t node7-win-x86 --debug  --out-dir D:/20170605 .**
![image](https://cloud.githubusercontent.com/assets/7929293/26774188/a4d8cc22-4a01-11e7-9cf5-562abb7853d2.png)

And **dest folder** is  my source code 
![image](https://cloud.githubusercontent.com/assets/7929293/26774280/195dac3e-4a02-11e7-9a41-3ae868d3564a.png)

**Comment by igorklopov** [comment]
`process.cwd()` obviously can not contain `C:\snapshot` component. Please `console.log(configFile)` before `require`.

**Comment by meiduo** [comment]
ok  thank you ~ and I can package my project but I try your example 
![image](https://cloud.githubusercontent.com/assets/7929293/26782665/4d9afd6a-4a27-11e7-892c-7318854f15ed.png)

and  when I input **http://localhost:8080/views/index.html**
![image](https://cloud.githubusercontent.com/assets/7929293/26782638/1f4b0374-4a27-11e7-8ac0-7ed5b9a8d0e7.png)

and in my project , I need input html in browser

**Comment by igorklopov** [comment]
Please check if a project works without pkg first. It is not intended to work that way.

**Comment by zhaifly** [comment]
try http://localhost:8080/index.html
