### ISSUE TITLE
Build Arguments

### ISSUE THREAD

**Issue by DerekTBrown** [zeit/pkg#129]
It would be really awesome to include the ability to "bake-in" various variables at build time as defaults.  Is this possible?

**Comment by igorklopov** [comment]
Do you mean global variables? Do you need them be evaluated at build step like time it was built? Is it acceptable to have a separate entrypoint for pkg. For example
```
global.variable = 'ok';
require('./main-entry-point-that-is-run-from-npm-start.js');
```

**Comment by DerekTBrown** [comment]
I have a makefile which I use to build the binary version of my application using pkg.  This makefile defines an environment variable which I would like to somehow persist into the binary.

**Comment by igorklopov** [comment]
So, i would recommend to write the value of the variable to some file before compilation.
```
echo $MYENVVAR > .env.txt
```
And pick up that file in the project by using
```
process.env.MYENVVAR = fs.readFileSync(path.join(__dirname, '.env.txt'), 'utf8');
```
Pay attention to `path.join` syntax. https://github.com/zeit/pkg#detecting-assets-in-source-code

**Comment by DerekTBrown** [comment]
This worked!  Thanks for your suggestion!
