### ISSUE TITLE
Error! tunneling socket could not be established

### ISSUE THREAD

**Issue by shopsoy** [zeit/pkg#130]
Hi,

I have set the linux proxy and also the npm proxy and both are working.

When I run the pkg . it can fetch the target but than fails due to socket not established.

 pkg .
> pkg@4.0.0
> Targets not specified. Assuming:
  node6-linux-x64, node6-macos-x64, node6-win-x64
> Fetching base Node.js binaries to: ~/.pkg-cache
  fetched-v6.10.3-linux-x64    [====================] 100%
> Error! tunneling socket could not be established, cause=connect EINVAL 0.0.12.56:80 - Local (0.0.0.0:0)
> Asset 'v2.3/uploaded-v2.3-node-v6.10.3-linux-x64' not found by direct link
> Error! tunneling socket could not be established, cause=connect EINVAL 0.0.12.56:80 - Local (0.0.0.0:0)

Can you help me?

Thanks in advance.

**Comment by igorklopov** [comment]
Seems just your network problem. Please check if github is available.

**Comment by shopsoy** [comment]
Hi,

Thanks for the reply but I can download stuff from GitHUB.
Is a specific port or protocol besides http/s?

Thanks in advance

**Comment by igorklopov** [comment]
Does it work?
```
curl -L https://github.com/zeit/pkg-fetch/releases/download/v2.3/uploaded-v2.3-node-v6.10.3-linux-x64 -o dummy
```

**Comment by shopsoy** [comment]
Hi,

Sorry for the delay.
The curl worked. If not this what could it be?

Regards
