### ISSUE TITLE
how I will pkg Grunt with external Gruntfile.js

### ISSUE THREAD

**Issue by pipiscrew** [zeit/pkg#132]
hi there, 

pack Grunt is possible and how ?

**Comment by igorklopov** [comment]
Why do you need to pack grunt? Run grunt, prepare everything with it, then run pkg. The executable should generally not need grunt since grunt is dev-mode only.

**Comment by pipiscrew** [comment]
I would like to have a more easier solution for **uncss**

**Comment by igorklopov** [comment]
Well, please describe in detail how you would like uncss to work with pkg?

**Comment by pipiscrew** [comment]
are places, where nodeJS + repository is not available... My thought is 

to have :

> uncss.exe
> Gruntfile.js //here uncss config
> a.html
> a.php
> a.css

**Comment by igorklopov** [comment]
Not a simple task to make `uncss.exe` because it needs and spawns phantomjs. However pkg has no obstacles/issues preventing to do it.
