### ISSUE TITLE
Static file inclusion and hosting path for use with Express

### ISSUE THREAD

**Issue by snovak** [zeit/pkg#133]
Hiya.  Firstly, awesome package!  Very useful.  I'm creating a self contained HTTP and websocket server with Express.  
My package.json includes; 
`  "pkg": {
    "assets": "assets/*"
  }`

Everything works great if I include (not link) all js and css in the index.html.  Index.html is pulled up by calling from index.js with:
`app.get('/', function (req, res) {
  res.sendFile(path.join(__dirname+'/assets/index.html'));
});`

Though, it seems I cannot reference/link any assets from the index.html file,, for instance: 
`<link rel="stylesheet" href="/assets/styles.css">`
-or-
`<script type="text/javascript" src="/assets/jquery.min.js" />`

If I try to access http://localhost:8080/assets/jquery.min.js directly, I get error: 

> Cannot GET: /assets/jquery.min.js

Any ideas?

**Comment by snovak** [comment]
BTW, I do have 
`app.use('/assets', express.static('assets'));`
....in index.js.  And, the functionality works as expected without having been packaged with pkg.

**Comment by igorklopov** [comment]
Please try `"pkg": { "assets": "assets/**/*" }` to crawl subdirectories. Glob info: https://www.npmjs.com/package/glob#glob-primer

**Comment by snovak** [comment]
That's it!  I guess I just thought assets/* would get any file in assets.  There are no recursive directories deeper than assets, all files are just in /assets in this case.  But, I'll take it.  Thank you!
