### ISSUE TITLE
AssertionError while building on Windows

### ISSUE THREAD

**Issue by simast** [zeit/pkg#134]
There seems to be an issue with this `assert()` statement:
https://github.com/zeit/pkg/blob/master/prelude/common.js#L127

On Windows the `normalizePath` function will always uppercase the drive letter, while the original input file path may have it in lowercase. Hence the equality assertion does not pass and the build is failing.

**Comment by igorklopov** [comment]
Test case please 🙏

**Comment by igorklopov** [comment]
I made that assert because i don't expect non-normalized after
https://github.com/zeit/pkg/blob/master/lib/walker.js#L105

**Comment by simast** [comment]
Hi Igor!

Looks like the issue is here:
https://github.com/zeit/pkg/blob/master/lib/index.js#L380

Original `entrypoint` is used with a lowercase drive letter (and not from `records` var). It does not get past walker `append` method and hence the  `normalizePath` function.

**Comment by igorklopov** [comment]
Yeah, that's true. I'll fix. Thanks 👍

**Comment by igorklopov** [comment]
Fixed in `pkg@4.1.1`.
