### ISSUE TITLE
Can't build arm6/arm7 on ubuntu

### ISSUE THREAD

**Issue by Pupix** [zeit/pkg#136]
Hello!

I am trying to build an armv6/armv7 executable to move from my ubuntu machine to a raspberry pi 3, but I am getting the following error:

```js
/home/pupix/.pkg-cache/v2.3/fetched-v8.0.0-linux-armv6: 1: /home/pupix/.pkg-cache/v2.3/fetched-v8.0.0-linux-armv6: Syntax error: word unexpected (expecting ")")
> Error! Error: Was not able to make bytecode for '{"nodeRange":"node8","platform":"linux","arch":"armv6","forceBuild":false,"binaryPath":"/home/pupix/.pkg-cache/v2.3/fetched-v8.0.0-linux-armv6"}' (read ECONNRESET)
    at Socket.onError (/usr/lib/node_modules/pkg/lib-es5/fabricator.js:35:8)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at emitErrorNT (internal/streams/destroy.js:62:8)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)

```

Any thoughts?

**Comment by Pupix** [comment]
I see this is a cross-cpu compatibility issues. This is not specified anywhere in the README, even more so it says that I can just run any combination of targets and it will work.

My ideal workflow is as follows:
`build app on my machine -> compile app -> deploy to raspberry`

How would I go about doing that with pkg?

**Comment by igorklopov** [comment]
Unfortunately currently you need to build the app on raspberry to be able to deploy to raspberry. https://github.com/zeit/pkg/issues/40#issuecomment-298469472

**Comment by igorklopov** [comment]
The solution:
https://github.com/zeit/pkg/issues/145#issuecomment-311150484
