### ISSUE TITLE
minification api

### ISSUE THREAD

**Issue by teddyarmagedon** [zeit/pkg#139]
It would be great to have minification api like - When file is about to be included in app, then you could see  file contents and return minified version of that.

**Comment by igorklopov** [comment]
I think that since there are much more steps than just minification, let leave this job for webpack.

**Comment by adonespitogo** [comment]
I couldn't get webpack to work with pkg. @igorklopov can you provide a minimal working webpack config?

**Comment by adonespitogo** [comment]
NVM. This solved my problem https://github.com/Metnew/webpack-pkg-plugin
