### ISSUE TITLE
Are there any plans to support linux-armv8?

### ISSUE THREAD

**Issue by czjs2** [zeit/pkg#146]
> Error! Unknown arch 'arm64'. Specify x64, x86, armv6, armv7

Are there any plans to support linux-armv8?

**Comment by igorklopov** [comment]
Node.js uses `arm64` term in both `process.arch` and `configure`. So, there will be `arm64` :)

**Comment by igorklopov** [comment]
Fixed in pkg@4.1.1. There are not precompiled binaries, but you can build them yourself bypassing `x64, x86, armv6, armv7` limitation.

**Comment by czjs2** [comment]
@igorklopov 
Thank you very much for your prompt reply. I'm compiling. I wish success.
