### ISSUE TITLE
How to pack express project

### ISSUE THREAD

**Issue by kipa-zhang** [zeit/pkg#150]
I tried to create file named `index.js` at `__dirname`,and copy `bin/www` into `index.js`

then at `package.json`

```
"pkg": {
    "targets": [
      "node6-win-x64"
    ]
  }
```

then run `pkg .` 

![1](https://user-images.githubusercontent.com/15901548/27580599-b7ffe9da-5b5d-11e7-89f0-17464b74179e.jpg)

How ?

**Comment by igorklopov** [comment]
```
  "bin": "index.js",
  "pkg": {
    "targets": [
      "node6-win-x64"
    ]
  }
```

**Comment by kipa-zhang** [comment]
Thanks very much!
