### ISSUE TITLE
Warning Cannot resolve and Error! Unexpected character '' (1:2)

### ISSUE THREAD

**Issue by jonahzheng** [zeit/pkg#156]
`> Warning Cannot resolve 'file'
  /opt/test/node_modules/handlebars/node_modules/uglify-js/node_modules/uglify-to-browserify/index.js
  Use a string literal as argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
> Error! Unexpected character '' (1:2)
  /opt/test/node_modules/autobahn/node_modules/google-closure-compiler/compiler.jar
`

**Comment by igorklopov** [comment]
`google-closure-compiler` is supported in pkg@4.2.0. Please upgrade!
