### ISSUE TITLE
Packed app stack trace on crash

### ISSUE THREAD

**Issue by GianlucaBortoli** [zeit/pkg#157]
I used this tool to pack my client-side application into a single executable in order to distribute it more easily. It worked like a charm with no issue at all and it's awesome.
Unfortunately, I noticed that if my application crashes for some reason the stack trace is not that informative.

I'll make it more clear explaining what happened to me:
* the **non-packed** application launched via `node /path/to/my/app.js` crashes with a clear stack trace saying where and what happened.
* the **packed** application with `pkg` launched in a shell crashes as well (obviously!), but the stack trace is not informative at all (error was on line 0).

I know that the packed application is now a raw binary and all the javascript code is inline and so on.
I wanted to ask whether someone encountered this kind of "issue" and has some hint about dealing with it.

**Comment by igorklopov** [comment]
Pass `--public` option to pkg. It is yet experimental feature. It takes sources of top-level project into executable to make it show full stack traces at run time.
