### ISSUE TITLE
Failed to lookup view in views directory

### ISSUE THREAD

**Issue by MM2404** [zeit/pkg#158]
I want to use "pkg" for my Express Node App. I'm using the node module "express-handlebars" for my templates.

**When I start the "pkg"-process there is only one warning** **-->** 
Warning Cannot resolve 'mod' 
C:\inetpub\wwwbasis\SiteMemoSafe\node_modules\express\lib\view.js
Use a string literal as argument for 'require', or leave it
as is and specify the resolved file name in 'scripts' option.

**my package.json looks like this:**
`{
  "name": "sitememosafe",
  "version": "1.0.0",
  "description": "",
  "bin": "app/app.js",
  "dependencies": {
    "async": "^2.5.0",
    "diff": "^3.2.0",
    "express": "^4.15.3",
    "express-handlebars": "^3.0.0",
    "fs-extra": "^3.0.1",
    "request": "^2.81.0"
  },
  "pkg": {
	"scripts": [],
	"assets": [
		"node_modules/**/*",
		"views/**/*",
		"app/css/*",
		"app/js/*",
		"app/gif/*"
	]
  },
  "devDependencies": {},
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "MM",
  "license": "ISC"
}`

**my app.js part where I set my views looks like this:**
`// Set view-engine
app.engine('handlebars', exphbs({
   defaultLayout: 'main',
   layoutsDir: '../views/layouts',
   partialsDir: '../views/partials'}
));

app.use('/css', express.static(__dirname + "/css"));
app.use('/js', express.static(__dirname + "/js"));
app.use('/gif', express.static(__dirname + "/gif"));

app.set('views', '../views');
app.set('view engine', 'handlebars');`

The windows executable was created and can be started without any errors When I now type 127.0.0.1:3000 to access my app the cli is showing me this error **-->**
(node:4664) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Failed to lookup view "startpage" in views directory "../views"

Used pkg version: 4.1.1
Used node version: 6.10.3

Do you have any suggestion to fix this error?

**Comment by unsaturated** [comment]
I had the same problem. It's critical that _all_ paths use `__dirname` including Handlebars. Make the following changes:

    app.set('views', path.join(__dirname, '..', 'views'));

    app.engine('handlebars', exphbs({
        defaultLayout: 'main',
        layoutsDir: path.join(__dirname, '..', 'views', 'layouts'),
        partialsDir: path.join(__dirname, '..', 'views', 'partials')}
    ));

**Comment by Avaray** [comment]
I think I have the same problem with Pug package. 

`  
  Warning Cannot resolve 'file'
  G:\AWESOME_PROJECT\node_modules\uglify-to-browserify\index.js
  Dynamic require may fail at run time, because the requested file
  is unknown at compilation time and not included into executable.
  Use a string literal as an argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
> Warning Malformed requirement for ''align-text''
  G:\AWESOME_PROJECT\node_modules\center-align\utils.js
`

**Comment by igorklopov** [comment]
@Avaray those are just compile time warnings. What are your run time errors?

**Comment by Avaray** [comment]
Short code example:

**app.js**
```
var pug = require('pug')
var path = require('path')
console.log(pug.renderFile(path.join(__dirname, 'themes/default/example.pug'), {
  name: 'Timothy'
}))
```

**example.pug**
```
p #{name}'s Pug source code!
```

And I'm getting that errors.

**Comment by MM2404** [comment]
@unsaturated Thanks for the suggest! I will test it on the weekend and tell you when it was successfull ;)

**Comment by MM2404** [comment]
@unsaturated Your suggestion works perfectly ;) Thank you very much! I'll close this issue now
