### ISSUE TITLE
SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by ecnormal** [zeit/pkg#159]
Hello All:
I am running ubuntu (virtual box vm) and have node.js,  npm working on my machine.
I installed pkg with a few warnings. (see below output of install).

---

root@vagrant-VirtualBox:/home/vagrant/node_modules# npm install -g pkg
npm WARN engine request@2.81.0: wanted: {"node":">= 4"} (current: {"node":"0.12.18","npm":"2.15.11"})
npm WARN engine har-validator@4.2.1: wanted: {"node":">=4"} (current: {"node":"0.12.18","npm":"2.15.11"})
npm WARN engine har-schema@1.0.5: wanted: {"node":">=4"} (current: {"node":"0.12.18","npm":"2.15.11"})
/usr/bin/pkg -> /usr/lib/node_modules/pkg/lib-es5/bin.js
pkg@4.1.1 /usr/lib/node_modules/pkg
├── simple-bufferstream@1.0.0
├── progress@2.0.0
├── in-publish@2.0.0
├── minimist@1.2.0
├── chalk@1.1.3 (supports-color@2.0.0, escape-string-regexp@1.0.5, ansi-styles@2.2.1, strip-ansi@3.0.1, has-ansi@2.0.0)
├── resolve@1.3.3 (path-parse@1.0.5)
├── stream-meter@1.0.4 (readable-stream@2.3.3)
├── multistream@2.1.0 (inherits@2.0.3, readable-stream@2.3.3)
├── globby@6.1.0 (object-assign@4.1.1, pify@2.3.0, array-union@1.0.2, pinkie-promise@2.0.1, glob@7.1.2)
├── fs-extra@3.0.1 (universalify@0.1.0, jsonfile@3.0.1, graceful-fs@4.1.11)
├── acorn@5.0.3
├── escodegen@1.8.1 (estraverse@1.9.3, esutils@2.0.2, optionator@0.8.2, esprima@2.7.3, source-map@0.2.0)
├── babel-runtime@6.23.0 (regenerator-runtime@0.10.5, core-js@2.4.1)
└── pkg-fetch@2.3.3 (byline@5.0.0, expand-template@1.0.3, semver@5.3.0, request-progress@3.0.0, unique-temp-dir@1.0.0, request@2.81.0)
----------------------------------------------------------------------------------------------------------------------------------

Then, when I ran pkg --help, i get the following error:

root@vagrant-VirtualBox:/home/vagrant/node_modules# pkg --help
/usr/lib/node_modules/pkg/node_modules/fs-extra/lib/index.js:3
const assign = require('./util/assign')
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/lib/node_modules/pkg/lib-es5/index.js:853:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
root@vagrant-VirtualBox:/home/vagrant/node_modules# 

---

Do you know what does this indicate? Any help to get it resolved would be greatly helpful.

Thank you!

Best,
Sam

**Comment by roccomuso** [comment]
Probably you're using an old version of node...

type `node -v` to see the version.

**Comment by lebanggit** [comment]
I have same issue. My Node version 
v0.10.25
