### ISSUE TITLE
not working with routing-controller

### ISSUE THREAD

**Issue by adnan-kamili** [zeit/pkg#160]
I tried to compile the koa app written using routing-controllers:

https://github.com/pleerock/routing-controllers/issues/211

It compiles but none of the controllers load.

**Comment by igorklopov** [comment]
Pass `--debug` option to pkg command line and try to find your controllers in the log. Are they there?

**Comment by adnan-kamili** [comment]
I already did that and they are present in the log. I also tried using assets instead of scripts, but still, it didn't work. The project is hosted online in case you want to check:

https://github.com/adnan-kamili/koa-web-api

**Comment by cyitianyou** [comment]
@adnan-kamili did you solved this question?
