### ISSUE TITLE
Error! tunneling socket could not be established

### ISSUE THREAD

**Issue by shopsoy** [zeit/pkg#166]
Hi,

I have set the linux proxy and also the npm proxy and both are working.

I can execute succesfully this command
    curl -L https://github.com/zeit/pkg-fetch/releases/download/v2.3/uploaded-v2.3-node-v6.10.3-linux-x64 -o dummy

When I run the 
         pkg server.js --target node6-linux-x64

it returns the following
> pkg@4.1.2
> Fetching base Node.js binaries to: ~/.pkg-cache
  fetched-v6.10.3-linux-x64    [                    ] 0%
> Error! tunneling socket could not be established, cause=connect EINVAL 0.0.12.56:80 - Local (0.0.0.0:0)
> Asset 'v2.3/uploaded-v2.3-node-v6.10.3-linux-x64' not found by direct link
> Error! tunneling socket could not be established, cause=connect EINVAL 0.0.12.56:80 - Local (0.0.0.0:0)

Can you help me?

Thanks in advance.

**Comment by igorklopov** [comment]
Since pkg is open source, i encourage you to debug yourself. You probably have odd internet setup or low bandwidth.
