### ISSUE TITLE
TypeError when running mac binaries

### ISSUE THREAD

**Issue by SamTebbs33** [zeit/pkg#167]
I'm trying to run a macOs (Sierra v10.12.5) binary I built with the standard options (command was `pkg run.js`) but am facing a TypeError (below).

```
$ ./run-macos
pkg/prelude/bootstrap.js:1173
      return wrapper.apply(this.exports, args);
                     ^

TypeError: Cannot read property 'errored' of null
    at /snapshot/elk/run.js:0:0
    at Array.forEach (native)
    at Object.<anonymous> (/snapshot/elk/run.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1173:22)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (pkg/prelude/bootstrap.js:1226:12)
    at run (bootstrap_node.js:469:7)
```

Here's the source I'm trying to build: https://github.com/SamTebbs33/elk

**Comment by igorklopov** [comment]
Try adding `"bin": "run.js"` property to your `package.json` and running `pkg package.json`

**Comment by SamTebbs33** [comment]
I deleted the old executables, ran that command and then ran `./elk-macos` but unfortunately the same error occurs

**Comment by igorklopov** [comment]
it should have line number in stack trace instead of `at /snapshot/elk/run.js:0:0`

**Comment by SamTebbs33** [comment]
Hmm, it's working perfectly now! Thanks for the info, I'll see if I can figure out what made it work.

**Comment by erwinverdonk** [comment]
Encountered the same issue and also had no line number in the stack trace. To get the correct line number I had to run the application directly from 'node' instead of 'pkg'. That way I got the correct error and stack trace and could solve the bug that caused this. Hopefully this approach is useful to others as well.

**Comment by rsrini7** [comment]
I am facing same issue in Windows - 8

![image](https://user-images.githubusercontent.com/5178105/35161111-39e50d78-fd65-11e7-8e05-faeff28f49ac.png)

**Comment by haouarihk** [comment]
for me there was an error in the bin.js file
try running node ./bin.js and fix the errors from there
