### ISSUE TITLE
Specify base binary cache directory

### ISSUE THREAD

**Issue by dizlexik** [zeit/pkg#173]
I need this for CI. And also it could be nice to include base binaries in my project's repository and specify them during builds. I'd propose an environment variable for the cache directory (similar to Yarn's YARN_CACHE_FOLDER) and a CLI option to use a specific base binary/binaries. Thoughts?

**Comment by dizlexik** [comment]
Awesome, thanks @igorklopov!

**Comment by igorklopov** [comment]
YW, Please wait for upcoming pkg release, or install from repo :)

**Comment by igorklopov** [comment]
`PKG_CACHE_PATH` env var is in pkg@4.2.0. Please upgrade!
