### ISSUE TITLE
Pkg fetch fail in GitlabCI, ENOENT problem

### ISSUE THREAD

**Issue by kMeillet** [zeit/pkg#174]
Hi zeit,

Pkg work well with GitlabCI but it seem "pkg-fetch" have some problem to download Node.js binary, got tons of "ENOENT ~/.pkg-cache" error in CI logs.

GitLab Ci Node.js Docker Image version != Pkg target(s) => Need a download, crash (ENOENT)
GitLab CI Node.js Docker Image version == Pkg target => Work well, don't need download (same version).

So, the only way to work with GitlabCI and Pkg is to select a Node.js version and stick with it, we can't compile multiple Node.js targets because fetching don't work and cause "ENOENT ~/.pkg-cache error".

It will output some logs tonight, maybe i need to create manually the ~/.pkg-cache and put Node.js binary ? I will try some things and update the issue later.

**Update :** better title ;) .

**Comment by igorklopov** [comment]
Hi @kMeillet! Please post stack trace for `ENOENT ~/.pkg-cache`. I need the line.

**Comment by igorklopov** [comment]
`PKG_CACHE_PATH` env var is in pkg@4.2.0. Please upgrade!

**Comment by kMeillet** [comment]
Love you.
