### ISSUE TITLE
Native addons problem about node-sass

### ISSUE THREAD

**Issue by llp0574** [zeit/pkg#176]
Hi,

The `node-sass` module has two addons both named as `binding.node` located in `/node_modules/node-sass/vendor/darwin-x64-51/` and `/node_modules/node-sass/vendor/darwin-x64-57/`.

How can I copy these two addons into the directory beside the three executables?

**Comment by llp0574** [comment]
Sorry, I forgot to clear an unused addon, actually it only has one addon.

**Comment by llp0574** [comment]
But after I using `cp` to copy the `binding.node` to the root directory the same as executables and execute the project in mac, there is still a missing binding problem occurred:

```
Error: Missing binding /snapshot/project-name/node_modules/node-sass/vendor/darwin-x64-57/binding.node
Node Sass could not find a binding for your current environment: OS X 64-bit with Node.js 8.x

Found bindings for the following environments:
  - Unknown environment (.DS_Store)
  - OS X 64-bit with Node.js 8.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass --force` to build the binding for your current environment.
at module.exports (/snapshot/hansight-atom-web/node_modules/node-sass/lib/binding.js:15:13)
    at Object.<anonymous> (/snapshot/hansight-atom-web/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (pkg/prelude/bootstrap.js:1173:22)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at Module.require (pkg/prelude/bootstrap.js:1083:31)
    at require (internal/module.js:11:18)
```

And I can sure I compiled the `node-sass` in the same version as the executables, so I feel confused, please help me if you figure it out, thanks.

And my node version is v8.0.0.

**Comment by llp0574** [comment]
I guess maybe I made a mistake in my deploy way for the native addon. So what's the correct way to deploy addon to the same directory as the executable?

**Comment by igorklopov** [comment]
I confirm the bug. Not really a bug, but node-sass uses it's unique way to check the presence of `.node` file.

**Comment by llp0574** [comment]
@igorklopov I check the source code of `node-sass` and found that it has the following code:
```
/*!
 * node-sass: lib/extensions.js
 */

var eol = require('os').EOL,
  fs = require('fs'),
  pkg = require('../package.json'),
  mkdir = require('mkdirp'),
  path = require('path'),
  defaultBinaryPath = path.join(__dirname, '..', 'vendor');
```
It seems that the `defaultBinaryPath` is the path it finds the `binding.node`, so what's your suggestion about this problem?

**Comment by llp0574** [comment]
@igorklopov Why you close this issue?

**Comment by llp0574** [comment]
@igorklopov Thanks for your fix!

**Comment by igorklopov** [comment]
Please download and try `pkg@4.1.4`
