### ISSUE TITLE
Can't open node_modules\phantom\lib\shim\index.js'

### ISSUE THREAD

**Issue by yucongo** [zeit/pkg#180]
// google.js
    const phantom = require('phantom');
    const path = require('path');

    var path1 = path.join(__dirname, 'node_modules\\phantom\\lib\\shim\\index.js');
    var path2 = path.join(__dirname,  'node_modules\\phantom\\lib\\shim\\function_bind_polyfill.js');

    const query = process.argv.slice(2).join(' ');
    const url = 'http://www.google.com/search?q=' + query;
    // console.log(url);

    async function fetch() {
        const instance = await phantom.create();
        const page = await instance.createPage();
        await page.on("onResourceRequested", function(requestData) {
            // console.info('Requesting', requestData.url)
        });

        const status = await page.open(url);
        const content = await page.property('content');
        await instance.exit();

        return content
    };

    async function start(){
        var content = await fetch();
        console.log(content);
    };

    start()

Windows 7, 32 bits
$ node -v
v8.2.1
phantom@4.0.5
$ pkg -v
4.1.3

$ pkg -t node8-win google.js

$ google.exe test
error: Can't open 'D:\snapshot\node_packaging\node_modules\phantom\lib\shim\index.js'

If I manually create the directory and copy **index.js** and **function_bind_polyfill.js** there, anything is fine.

I tried to include the files with "assets" in package.json (pkg -c package.json google.js), I aslo tried with C:, the same result.

How can I fix the problem? Thanks a lot. pkg is great!

**Comment by igorklopov** [comment]
Fixed in pkg 4.2.0
