### ISSUE TITLE
compressing executable with gzexe or upx problem

### ISSUE THREAD

**Issue by serkanp** [zeit/pkg#184]
hi igor :)
my main application is now 95 mb when compiled.. 
i want to use upx or gzexe to reduce its size. 
when upx it becomes 22mb,with  gzexe 24 mb.

when i compile pkg'd application to reduce size with upx or gzexe i have some problems:
test environment: 
i installed sqlite3 and using it when compiled with pkg without any problem. 
i put the node_sqlite3.node file near the compiled app.. 

- with gzexe: 
serkans-iMac:nodeplayernode8 serkan$ gzexe nodeplayer1
nodeplayer1:	   74.7%
serkans-iMac:nodeplayernode8 serkan$./nodeplayer
Error: Cannot find module '/snapshot/nodeplayernode8/node_modules/sqlite3/lib/binding/node-v57-darwin-x64/node_sqlite3.node'
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1217:46)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at Module.require (pkg/prelude/bootstrap.js:1101:31)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/snapshot/nodeplayernode8/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (pkg/prelude/bootstrap.js:1191:22)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)

- with: upx:
serkans-iMac:nodeplayernode8 serkan$ upx -9 nodeplayer1
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2017
UPX 3.94        Markus Oberhumer, Laszlo Molnar & John Reiser   May 12th 2017

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
  95844440 ->  22454928   23.43%   macho/amd64   nodeplayer1                   

Packed 1 file.
serkans-iMac:nodeplayernode8 serkan$ ./nodeplayer1
 it enters to: > 

as we got the problem when we change the resources of file with resourcehacker , the packed app enters to command prompt >

**Comment by igorklopov** [comment]
About `sqlite3.node` - it may happen if your tool performs operation similar to `strip` utility (strips symbols from the executable that are needed for native addon to work).

About Upx - here is an issue about `upx`. https://github.com/zeit/pkg/issues/121#issuecomment-309204155. Be sure you preserve overlay by `overlay=copy`. Also, upx compatibility will be improved in future.

**Comment by serkanp** [comment]
ubuntu 16, upx 3.94, pkg 4.2.5 
$ pkg -t node8-linux app.js 
$ upx -1 app --overlay=copy -o app1
$ ./app1
>
still the same it enters to: >
