### ISSUE TITLE
Include *.js files into binary

### ISSUE THREAD

**Issue by RidgeA** [zeit/pkg#185]
Hello!.
May be I have some incomprehension how this tool works.
Does it pack all .js files (my app and node_modules/ files) or not?

When I trying to build app using
`pkg -t node8-linux-x64 package.json`
command I get a binary that could be run only inside directory, where *.js files placed.

Thank you!

**Comment by igorklopov** [comment]
`pkg -t node8-linux-x64 package.json -d` to see if they are taken into executable. Be sure you explicitly `require` those files.

**Comment by RidgeA** [comment]
Thank you for answer.
Yes they are taken.
The problem was in `config` module - it loads configuration files dynamical, so i also should copy `./config` directory with binary file.

**Comment by igorklopov** [comment]
Great! Feel free to reopen on something new :)
