### ISSUE TITLE
Express App Fails to package [create-react-app]

### ISSUE THREAD

**Issue by Shadowys** [zeit/pkg#189]
Similar problem to https://github.com/zeit/pkg/issues/158 but I'm using Jade for my application.

```
$ node --version
v7.10.1

$ pkg --version 
4.2.2
```

Main difference from #158 is here
```
app
  .set('views', path.join(__dirname, 'views'))
  .set('view engine', 'jade')
```

Error message: 
```
Error: Failed to lookup view "error" in views directory
```

**Comment by MM2404** [comment]
Can you tell me where your app.js/index.js is located? And where is your 'views' directory located?

In #158 my folder structure was "app/app.js" and "views/partials" so I had to use `'..' in path.join()`.

Have you set your views directory in the package.json file as an asset?

**Comment by Shadowys** [comment]
I've been using the default create-react-app folder structure, without any nested folders for any of the source code.

**Comment by MM2404** [comment]
So is your views folder on the same level as your "src" folder? And you don't have partials or layouts right?

**Comment by Shadowys** [comment]
Yes

**Comment by MM2404** [comment]
Okay., try to change your 
`app.set('views', path.join(__dirname, 'views'))`

to this:

`app.set('views', path.join(__dirname, '..', 'views'))`

and don't forget to set `views/**/*` to you "pkg" area in package.json:
`"pkg": { "scripts": [], "assets": ["views/**/*"] }`

**Comment by Shadowys** [comment]
Okay I got it. Apparently I have to pass my package.json as a config

**Comment by i2chris** [comment]
I'm having the same issue. 

`Apparently I have to pass my package.json as a config`  

What do you mean by this?

**Comment by danieltanfh95** [comment]
Usage

npm install -g pkg

After installing it, run pkg --help without arguments to see list of options.

The entrypoint of your project is a mandatory CLI argument. It may be:

    Path to entry file. Suppose it is /path/app.js, then packaged app will work the same way as node /path/app.js
    Path to package.json. Pkg will follow bin property of the specified package.json and use it as entry file.
    Path to directory. Pkg will look for package.json in the specified directory. See above.
