### ISSUE TITLE
Allow executable to use external files

### ISSUE THREAD

**Issue by piotte13** [zeit/pkg#195]
The .exe should be able to call or read external files which are not bundled inside the executable.
As an example, we have a config.json file that is used by the application and we want to edit the file anytime without having to rebuild the entire package.
Right now, it seems there is no way to communicate with data that is not bundled.

**Comment by sergiodxa** [comment]
You can do that if you use `fs` to read the file, in the case of a JSON you can read it as a string and parse it to an object with `JSON.parse`.

**Comment by igorklopov** [comment]
Right. `require('./config.json')` will not work. You should use `fs` and additionally you should use `path.dirname(process.execPath)` or `process.cwd()` to get the path to your config. For example `fs.readFileSync(path.join(path.dirname(process.execPath), 'config.json'))`

**Comment by piotte13** [comment]
Thank you for your fast reply! 
This will do for json files. But, what if I have a resource folder full of images and fonts that I want to change after the build? Like you said, I could load them with `fs` but they are part of my front-end bundle and front end code can't use file io. That means I would need to serve these files from the backend which is quite weird and adds complexity.

**Comment by igorklopov** [comment]
You will need to serve them from backend anyway (without pkg). Aren't you?

**Comment by piotte13** [comment]
Okay, let's approach this differently.

Let's say we have an express server that hosts a one-page application like angular or react-redux.  The express server will send the `index.html` on any request by the browser, now, that `index.html` has its own dependencies (managed by Webpack) which are not related to the express server. Isn't there a way to separate frontend and backend code?  
The question is, can we bundle **ONLY** the backend code inside the .exe and then this .exe will serve an external front end code to the browser? 
This way, we do not have to make a new bundle every time something changes in the UI even if the backend is untouched. MVC pattern style.

Thanks for your time!

**Comment by agauniyal** [comment]
unless you've hardcoded `index.html` inside your backend code, this should work fine 🤔 .

**Comment by piotte13** [comment]
I made it work finally!
Basically, replace `__dirname` with `process.cwd()` for files you don't want to bundle.
Thanks!

**Comment by otissv** [comment]
I got this working with `process.cwd()`. 

So as not to have to reload the server after each external file change I delete the file from the`require.cache`.

```
app.get('/test', function(req, res) {
    const file = path.join(process.cwd(), '../test.js');
    delete require.cache[require.resolve(file)];
    const test = require(file);
    res.json(test);
});
```

**Comment by otissv** [comment]
I got this working with `path.dirname(process.execPath`.  `process.cwd()` was working when I moved the exe to another directory and tried to open it in finder.

```
function getExternalFile (pathToFile) {
    const filePath = path.join(path.dirname(process.execPath), pathToFile);
    delete require.cache[require.resolve(filePath)];
    return require(filePath);
}
```
As to not have to reload the sever on exteral file changes, the file is delete from require cache before being required.

To get app the files in a directory you can glob the directory and the require the files with the function.
