### ISSUE TITLE
Bug? : pkg doesn't work as expected with scoped module name

### ISSUE THREAD

**Issue by rmharrison** [zeit/pkg#199]
## Behaves as expected when module name is unscoped

package.json
```json
  "name": "foo"
```

```bash
>>> npx pkg . --targets node6-linux,node6-macos,node6-win --out-path='./bin/
```

```bash
>>> ls -R bin/`
foo-linux  foo-macos  foo-win.exe
```

## However, with a scoped module name...
Scoped module in package.json
```json
  "name": "@org/foo"
```

```bash
>>> npx pkg . --targets node6-linux,node6-macos,node6-win --out-path='./bin/
```

```bash
>>> ls -R bin/`
bin/:
@org

bin/@org:
foo-linux  foo-macos  foo-win.exe
```

I expected the files to be placed directly in `bin/`, rather than `bin/@org`.

**Comment by rmharrison** [comment]
Thank you @igorklopov! Wasn't sure whether this was a bug, or was you'd intended.

**Comment by igorklopov** [comment]
You are welcome!

**Comment by igorklopov** [comment]
Please upgrade to pkg@4.2.4

**Comment by SimenB** [comment]
This should be noted as a breaking change
