### ISSUE TITLE
Packaging a FeathersJS App

### ISSUE THREAD

**Issue by pipeserrano** [zeit/pkg#200]
Can I chain a gulp pipe to the flow of your packaging?

**Comment by igorklopov** [comment]
Hi! I did not manage to reproduce. Please post your pkg command line and output.

**Comment by pipeserrano** [comment]
Can I add a gulp pipe to the flow of your packaging

**Comment by igorklopov** [comment]
You can create some gulp wrapper for pkg and use it.

**Comment by pipeserrano** [comment]
Any example I could look at? thank you

**Comment by igorklopov** [comment]
No example. Just an idea. Think of it as running a custom app from gulpfile.
