### ISSUE TITLE
Set Version Property at Windows Executable

### ISSUE THREAD

**Issue by haeferer** [zeit/pkg#201]
Hi, 

is there a way / idea to set / specify the version (or any other executable property like copyright etc) of the (windows)-executable. currently all these informations are blank.

Thx for your help and creating this cool tool

**Comment by haeferer** [comment]
the only way i found is to use a tool like RCEDIT (from electron framework) to manipulate the executable after creation [https://github.com/electron/rcedit](https://github.com/electron/rcedit)

**Comment by igorklopov** [comment]
Please use RCEDIT. Pkg is not planned to provide this functionality. Let every tool do it's job.

**Comment by haeferer** [comment]
rcedit cant be use ( like #149). As far as i understood, there is no ressource present in the executable. RCEDIT can only edit ressource Elements if they exist!

**Comment by igorklopov** [comment]
@haeferer ok, i will look into #149 soon

**Comment by haeferer** [comment]
Thx a lot
