### ISSUE TITLE
Code that is using the object spread operator can't be packaged

### ISSUE THREAD

**Issue by pkeuter** [zeit/pkg#206]
For example: 

When running `pkg index.js`:
```
const testObject = {};
const spreaded = {...testObject};
```
throws this error:
```
Error! Unexpected token (2:18)
  index.js
```

Node handles spread since v8.3: http://node.green/#ESNEXT-candidate--stage-3--object-rest-spread-properties. By default, pkg uses version 8.0.0 of Node, but when passing `-t latest`, it uses 8.3, I would assume object spread should work when using version 8.3.

**Comment by boshido** [comment]
I'm using babel-register too.
For me I faced problem of "..." syntax, it caused pkg throw an error when it found "..." command
```
> pkg@4.2.4
> Error! Unexpected token (25:84)
  /home/com/app/apis/admin/admin-driver.flow.js
```
Work fine for running node index.js

**Comment by krjj** [comment]
Spread operator does not work with node version 8.6.0

**Comment by santimendoza** [comment]
I facing the same issue. Node 8 LTS DO support spread object operator. But when I try to package my project using node8 in pkg, I get a `Unexpected token`.

Any help or solution?

**Comment by Kikobeats** [comment]
same problem :((

**Comment by rjhilgefort** [comment]
Facing this problem as well.

**Comment by jonathanprl** [comment]
Same here with 8.9.0

```
 pkg@4.3.0
> Fetching base Node.js binaries to PKG_CACHE_PATH
  fetched-v8.9.0-win-x64       [====================] 100%
> Error! Unexpected token (74:59)
```

**Comment by ramiel** [comment]
Same here.

**Comment by ashking** [comment]
Any solution to this problem?

**Comment by kalinkrustev** [comment]
Try setting ecmaVersion to 9 here:
https://github.com/zeit/pkg/blob/master/lib/detector.js#L334

**Comment by SirArslaan** [comment]
Same here

**Comment by igorklopov** [comment]
I'll be taking care of these shortly, with some more updates coming to `pkg`. Thank you!

**Comment by Kikobeats** [comment]
Love what is ZEIT doing these days for the web in terms of OSS, but definitely, this repository needs more attention.

A Pull Request related to spread operator has merged days ago:
https://github.com/zeit/pkg/pull/379

is the PR closing this issue?

We can find at least more than one issue related to spread operator that is not closed:
https://github.com/zeit/pkg/issues/352. Why?

The only thing that we have is a message from the main contributor saying "yep, no problem, news coming soon," but what news? Will all the issues be solved magically? why so little information?

Just I want to understand how are you doing to maintain this repository and trying to push forward.

**Comment by garthk** [comment]
Fixed in 4.3.1.

**Comment by garthk** [comment]
@santimendoza?

**Comment by santimendoza** [comment]
@garthk I hadn't test it with that version. I'll test it and let you know

**Comment by santimendoza** [comment]
It worked for me in the latest version

**Comment by estambakio-sc** [comment]
`4.3.1` still breaks on rest operator.

**Comment by Kikobeats** [comment]
It is still present at `4.3.2`

```
> Error! Binding rvalue (18:31)
```

where the line of code is

```js
module.exports = async ({ url, ...opts }) => {
```

**Comment by igorklopov** [comment]
Thanks!

**Comment by OysteinAmundsen** [comment]
Still breaks for me:
```
> Error! Unexpected token, expected ";" (11:5)
  D:\dev\app\node_modules\normalize.css\normalize.css
error Command failed with exit code 2.
```

**Comment by arpitprod** [comment]
@OysteinAmundsen any solution? I'm also facing same error

**Comment by igorklopov** [comment]
@OysteinAmundsen @arpitprod does it fail with `require("normalize.css")` only? How the code looks like?

**Comment by arpitprod** [comment]
@igorklopov yes, [this](https://github.com/zeit/pkg/issues/317#issuecomment-564960792) is solution for me

**Comment by igorklopov** [comment]
@arpitprod ok, but please try `pkg@4.4.2` in case no workaround is needed with 4.4.2

**Comment by arpitprod** [comment]
it's working fine now after update pkg
