### ISSUE TITLE
Support opn

### ISSUE THREAD

**Issue by FallingSnow** [zeit/pkg#207]
Using [opn](https://github.com/sindresorhus/opn) in a packaged program results in the error below.

```
Error: spawn /snapshot/deploy/node_modules/opn/xdg-open ENOENT 
```

Is there a special setting on pkg that I am supposed to use?

More info: https://github.com/sindresorhus/opn/issues/61

**Comment by harisvsulaiman** [comment]
I got the same issue, it Seems like pkg doesn't package shell scripts. @igorklopov could you elaborate the reason for closing this issue.

**Comment by FallingSnow** [comment]
He closed the issue via a commit, which means he fixed the issue. The fix may not have hit a stable version yet.

**Comment by harisvsulaiman** [comment]
@FallingSnow Did not know that! thank you!

**Comment by Mikanebu** [comment]
@FallingSnow  When will you release a stable version with this fix? Thanks

**Comment by FallingSnow** [comment]
I have no power over this repository or pkg.

**Comment by Mikanebu** [comment]
@igorklopov When will you release a stable version with this fix? Thanks

**Comment by igorklopov** [comment]
@Mikanebu please try again with pkg@4.2.5

**Comment by harisvsulaiman** [comment]
@igorklopov seems to be working for me!

**Comment by anuveyatsu** [comment]
@igorklopov this didn't help me and I'm getting following warning:

```
> Warning Cannot include file %1 into executable.
  The file must be distributed with executable as %2.
  node_modules/opn/xdg-open
  path-to-executable/xdg-open
```

can this be a reason? Any suggestion would be very helpful.

**Comment by daviscodesbugs** [comment]
Seeing the same issue as @anuveyatsu
