### ISSUE TITLE
why the project example run "pkg ."，the generate file execute with error

### ISSUE THREAD

**Issue by junerleer** [zeit/pkg#208]
Environment
system：win 7
node：8.3.0

the error pic ：
![error](https://user-images.githubusercontent.com/14024936/29769502-3e8645fe-8c1d-11e7-9c2b-70c055b0ecdb.png)

**Comment by igorklopov** [comment]
Please run `npm intsall` before compilation

**Comment by junerleer** [comment]
thanks for your reply.

my real problem is I used the framework called [thinkjs v2.2](https://thinkjs.org/en/doc/2.2/index.html)

the structure is as bellow
**--app/**                                       code after babel
**--node_modules/**                      
**--www/**
**--www/production.js**               entry.js
**--www/static/**                          assets resources
**--view/**                                     view templates
**--package.json**

Real project is complex, so I use the thinkjs-cli create the easiest demo. Then I config the package.json and modified the entry.js.

--package.json--
`
"bin":"www/production.js",
  "pkg":{
    "assets":["view/**/*","www/static/*"],
    "scripts":["app/*.js"]
  },
`

--production.js--
`
var thinkjs = require('thinkjs');
var path = require('path');

var rootPath = path.dirname(__dirname)

var instance = new thinkjs({
  APP_PATH: path.join(rootPath,'app'),
  RUNTIME_PATH: path.join(rootPath,'runtime'),
  ROOT_PATH: rootPath,
  RESOURCE_PATH: path.join(rootPath,'www'),
  env: 'production'
});

instance.run(true);
`
I can generate the executable file successfully, but it stills run with error
![default](https://user-images.githubusercontent.com/14024936/29775016-37ca0610-8c36-11e7-9308-3b070574fec7.png)

the test demo url is "https://github.com/junerleer/pkg_demo"

**Comment by junerleer** [comment]
@igorklopov  I am confused about the snapshot,I really config the pkg options in package.json
