### ISSUE TITLE
Packaging loopback application

### ISSUE THREAD

**Issue by asaf050** [zeit/pkg#220]
Hey,

Does anyone have experince with packaging application built with loopback framework?

Thanks

**Comment by asaf050** [comment]
I solved the problem, please see this repo as a reference
https://github.com/asaf050/loopback-pkg-ready

**Comment by sebfindling** [comment]
@asaf050 could you please explain what did you change to make it compilable?

**Comment by asaf050** [comment]
@sebfindling only package.json file with pkg tags
