### ISSUE TITLE
Applying Patches Error: spawn patch ENOENT

### ISSUE THREAD

**Issue by twmarr** [zeit/pkg#236]
I cannot get past this error to build my app and I am not sure why it doesn't just download the binaries.
 
pkg server.js -o server.exe -t node6-win-x64 -debug
> pkg@4.2.4
> Building base binary from source:
  built-v6.10.3-win-x64
> Cloning Node.js repository from GitHub...
  git                          [====================] 100%
> Checking out v6.10.3
> Applying patches

> Error! Error: spawn patch ENOENT
    at exports._errnoException (util.js:1020:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:197:32)
    at onErrorNT (internal/child_process.js:376:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

I will add that my app will build and run if I use EncloseJS.  I realize EncloseJS is not a solution, but it seems that it doesn't have the spawn issue.

**Comment by twmarr** [comment]
After I cleaned up excess modules, this is no longer an issue.

**Comment by cyrilcyril70** [comment]
> pkg@4.2.5
> Error! Entry file/directory is expected
  Pass --help to see usage information

E:\pkg\pkg\pe>pkg -d -b .
> pkg@4.2.5
> Building base binary from source:
  built-v6.10.3-win-x64
> Cloning Node.js repository from GitHub...
  git                          [====================] 100%
> Checking out v6.10.3
> Applying patches

> Error! Error: spawn patch ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)


I'm facing the same issue while building the 'pkg' . can u help me out of this issue.

**Comment by twmarr** [comment]
I removed modules that I was not actually using and this error went away.

**Comment by cyrilofc** [comment]
I installed some packages globally which is needed for my project , after building it working correctly. so that error gone. Thank you @twmarr

**Comment by JohnKnust** [comment]
Hi! I tried a few hours to get it working. It's a little private project with just some hello world in it. 
It would be very helpful to get some more information to solve the problem. 
```
>pkg -db sample.js -t win
> pkg@4.3.1
> Building base binary from source:
  built-v9.2.1-win-x64
> Cloning Node.js repository from GitHub...
  git                          [====================] 100%
> Checking out v9.2.1
> Applying patches

> Error! Error: spawn patch ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:379:16)
    at process._tickCallback (internal/process/next_tick.js:114:19)
```

**Comment by SmirnovM91** [comment]
+1

**Comment by BCsabaEngine** [comment]
A reason of error is: linux systems contains (not every distro by default) a command called "patch", that can upgrade code files (cpp) about a diff file (patch). Windows systems does not contains these utility, so spawn('patch') failed.

If you can leave without nodejs patches (bugfixes, etc.) you can run the compilation after modify file \node_modules\pkg\node_modules\pkg-fetch\lib-es5\build.js 

Change this line (169):
```
return [4 /*yield*/, utils_1.spawn('patch', args, { cwd: nodePath, stdio: 'inherit' })];
```

to this:
```
return [4 /*yield*/, [2]];
```

Or you can download a very old application from here: http://gnuwin32.sourceforge.net/packages/patch.htm that can run as a patch.exe (I have NOT tried it)

**Comment by jesec** [comment]
> A reason of error is: linux systems contains (not every distro by default) a command called "patch", that can upgrade code files (cpp) about a diff file (patch). Windows systems does not contains these utility, so spawn('patch') failed.
> 
> If you can leave without nodejs patches (bugfixes, etc.) you can run the compilation after modify file \node_modules\pkg\node_modules\pkg-fetch\lib-es5\build.js
> 
> Change this line (169):
> 
> ```
> return [4 /*yield*/, utils_1.spawn('patch', args, { cwd: nodePath, stdio: 'inherit' })];
> ```
> 
> to this:
> 
> ```
> return [4 /*yield*/, [2]];
> ```
> 
> Or you can download a very old application from here: http://gnuwin32.sourceforge.net/packages/patch.htm that can run as a patch.exe (I have NOT tried it)

This is absolutely wrong. The binaries would not work at all if the patches are not applied. 

You must make the `patch` utility available in the PATH. It can usually be installed with the package manager of your distribution. On Windows, some tools such as Git Bash bundle this utility.
