### ISSUE TITLE
> Warning Cannot include addon %1 into executable.

### ISSUE THREAD

**Issue by Nilesh0101** [zeit/pkg#240]
Hello,

I'm getting warnings in pkg while using aerospike.
```
node --version - v6.7.0
npm --version - 3.10.3
pkg --version - 4.2.4
```
pkg -t node6-linux-x64
```
> pkg@4.2.4
> Warning Cannot include addon %1 into executable.
  The addon must be distributed with executable as %2.
  /home/nilesh/test_code/shared/node_modules/aerospike/build/Release/aerospike.node
  path-to-executable/aerospike.node
```
package.json
```
  "pkg": {
    "assets": "../shared/node_modules/aerospike/build/Release/obj.target/aerospike.node:../shared/node_modules/aerospike/build/Release/aerospike.node",
  }
```

**Comment by jgoux** [comment]
Hello,

for me the solution was to manually copy the `oracledb.node` file along with the generated binary. You can't encapsulate the .node within the binary I think.

What would be great is to have an option like `--copy-native` so we don't have to manually copy the native modules.

**Comment by Nilesh0101** [comment]
Hi Julien,

Thanks for the reply.
And yes copying .node files with the created executable solved my problem too. Yes we can not encapsulate them together.
But still struggling with "https://github.com/zeit/pkg/issues/241".
have not found any solution for this.

**Comment by designbyadrian** [comment]
@jgoux Copy the file to where? Where is `path-to-executable`?

**Comment by maheshjukanti** [comment]
i had same issue. how can i solve this issue
