### ISSUE TITLE
pkg with ES Modules

### ISSUE THREAD

**Issue by msell** [zeit/pkg#255]
Does pkg support ESModules with the .mjs extension?  Here is the command I'm running
```
pkg . --targets latest-macos-x64
```
I am seeing the following error:
Error [ERR_MISSING_MODULE]: Cannot find module ./main.mjs

my entry point or bin file is a standard .js file that imports the .mjs file like this:
```
#!/usr/local/bin/node
require = require('@std/esm')(module)
module.exports = require('./main.mjs')
```

**Comment by msell** [comment]
the entire source is here: https://github.com/msell/nfl-odds-cli 
My pkg command is in the npm scripts

**Comment by msell** [comment]
I learned in the Zeit Community slack channel:
> pkg relies on https://github.com/zeit/pkg-fetch which come with prepackaged node.js version. The latest in the project is v8.3.0
I guess I'll just keep an eye on it and wait for it to become available.

**Comment by igorklopov** [comment]
Currently the latest is 8.6.0. Just pass `-t node8.6.0` as cli argument. However mjs is not supported yet.

**Comment by DavidScentys** [comment]
Hi there,
does anyone know if mjs and ES6 modules are now supported with pkg ?
Thank you for your help,
David.

**Comment by FranklinYu** [comment]
@msell Please re-open this. `pkg-fetch` is no longer a road blocker, we should start to work in pkg to support ES modules.

**Comment by FranklinYu** [comment]
I came across this today and found #439 to be related.

**Comment by GeneralBaduar** [comment]
I find it weird that even though node 16 is in Active LTS, neither ```pkg``` or ```nexe``` work with modules and nothing seems to move in this direction.

I have moved my project to modules because some npm packages are module only now. It looks like at this point in time I either have to use old packages or can't compile my project (sad)

https://nodejs.org/en/about/releases/

**Comment by thiagoanselmo** [comment]
@GeneralBaduar 

Time the same problem.
I left my code as a module, used the rollup to build for CJS and had no problems.

If you want I can post my rollup code.

**Comment by GeneralBaduar** [comment]
> @GeneralBaduar
> 
> I had the same problem I left my code as a module, used the rollup to build for CJS and had no problems.
> 
> If you want I can post my rollup code.

Yes, sure. Any sample is appreciated. Thank you!

**Comment by alancnet** [comment]
Re-open please

**Comment by robertsLando** [comment]
It's a dup issue, see
