### ISSUE TITLE
Trying to read System32 Roaming folder

### ISSUE THREAD

**Issue by dannydeut** [zeit/pkg#258]
Really like this module. However I am facing some issues reading files from the system32 roaming folder. The folder I am trying to read is: C:/Windows/System32/config/systemprofile/AppData/Roaming/ApplicationName. This folder is created by another of our C++ applications. 

When I run the node directly I am able to read this directorty (node dist/index.js). But when I use 'pkg' to create an executable and run the executable, it returns an ENOENT error that the folder does not exist.

Any ideas what I am doing wrong? Or what I should do?

**Comment by igorklopov** [comment]
Please supply some code. No data is stored there by pkg, but i am sure there should be no difference.

**Comment by dannydeut** [comment]
Issue can be closed. I was trying to access the 64bits app data folder with an 32bits executable. I was overlooking the 32bits target in my build script. Changing the target to win-x64 did the trick.
