### ISSUE TITLE
Issues with spawning bash

### ISSUE THREAD

**Issue by denysdovhan** [zeit/pkg#259]
I'm trying to build binaries for one of NodeSchool's workshoppers called [`learnyoubash`](https://github.com/denysdovhan/learnyoubash).

The problem is that it spawns `bash` with one of the solution files. I wondering it tries to spawn:

```bash
bash /snapshot/learnyoubash/exercises/hello_world/solution/solution.bash
```

However, there's not such directory as `/snapshot/learnyoubash/exercises/hello_world/solution/solution.bash`  in my system, it's in the binary itself.

How can I get out of this situation?

### Steps to reproduce

1. `git clone git@github.com:denysdovhan/learnyoubash.git`
1. `cd learnyoubash`
1. `git checkout building-binaries`
1. `npm run build`
1. `./build/learnyoubash-macos` and choose the **HELLO WORLD** exercise.
1. `./build/learnyoubash-macos verify ./exercises/hello_world/solution/solution.bash`

### Expected behavior

Packaged binary should spawn `bash` with package files, not global ones.

### `pkg` field in `package.json`

```json
{
  "pkg": {
    "scripts": [
      "exercises/**/*.js",
      "i18n/**/*.{js,json}",
      "utils/**/*.js",
      "node_modules/workshopper-adventure/{default,lib,i18n}/**/*.{js,json}"
    ],
    "assets": [
      "exercises/**/*.*.md",
      "exercises/**/solution/*.bash",
      "i18n/**/*.md",
      "node_modules/workshopper-adventure/i18n/{footer,usage}/*.md"
    ]
  }
}
```

**Comment by igorklopov** [comment]
So imagine that your executable is shipped alone. Then `bash` files are inside it, they are accessible via `/snapshot` path, but only if you use node's `fs` module functions. If you want to run a system app against internal files, you need to extract them from executable to real file system. Because system app can obviously see real file system, not internal fs of executable.

**Comment by igorklopov** [comment]
In your case you can detect pkg by `process.pkg`. You can also
```
const body = fs.readFileSync(require.resolve('../exercises/**/solution/some-file.bash'));
const realFileName = path.dirname(process.execPath) + '/bash-files/some-file.bash';
fs.writeFileSync(realFileName, body);
spawn('bash', [ realFileName ]);
```

**Comment by denysdovhan** [comment]
I've got it. Thanks for your response!
