### ISSUE TITLE
Question about process.env.NODE_ENV when running pkg

### ISSUE THREAD

**Issue by micooz** [zeit/pkg#261]
I have a `module.js` which requires different type of modules from different directory:

```js
if (process.env.NODE_ENV === 'development') {
  require('babel-register');
  module.exports = require('../src');
} else {
  module.exports = require('../lib');
}
```

when running pkg, it seems analyze deps into both `require('../src')` and `require('../lib')`. Modules in `src` fail to compile because it has new language features which must be transpiled by babel first.

I also notice that in the previous version of pkg, it just includes `require('../lib');` by judging NODE_ENV first.

Is it a bug or something that expected?

**Comment by igorklopov** [comment]
I am sure all versions of pkg should follow both `../src` and `../lib` to collect files. Please use `require('../src', 'must-exclude')` syntax to tell pkg to ignore `../src`.

**Comment by micooz** [comment]
@igorklopov thx, it works well, maybe we should make a document of `must-exclude`?

**Comment by igorklopov** [comment]
Right. Later. I doubt to leave this functionality as is.
