### ISSUE TITLE
app closes immediately after executing it. 

### ISSUE THREAD

**Issue by SunriseM** [zeit/pkg#262]
It closes too fast before i can see if theres an error. Debugging the pkg process doesn't show anything wrong. 

pkg@4.2.5
node@8.6.0

EDIT:
i added this to log any process error 

`process.on('uncaughtException', function (err) {
	fs.writeFileSync('log.txt', err);
});`

and got this: 

> Error: ENOENT: no such file or directory, uv_chdir
> 1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.

i get this warning when compilating:

> Warning Cannot resolve 'process.cwd() + '/config.json''
>   C:\PATH\app\utils.js
>   Dynamic require may fail at run time, because the requested file
>   is unknown at compilation time and not included into executable.
>   Use a string literal as an argument for 'require', or leave it
>   as is and specify the resolved file name in 'scripts' option.

I saw on slack someone with the same problem that used the same code to load an external json file. 

i tried this one too: 
`fs.readFileSync(path.join(path.dirname(process.execPath), 'config.json'))` and didnt work either. any suggestion?

**Comment by syokujinau** [comment]
same problem

**Comment by IndiumCrypto** [comment]
Problem solved 10/10 good content guys.

**Comment by XFaonAE** [comment]
At a company this big, the best they could do Is link to an issue, absolutely ridiculous, they didn't even bother to reply

**Comment by XFaonAE** [comment]
The issue still happens, and ive tested it on multiple devices

**Comment by XFaonAE** [comment]
after updating, now it doesnt even bother to compile.....

**Comment by robertsLando** [comment]
@XFaonAE this package is not maintained by Vercel anymore from a long time, it's maintained by outside collaborators in their free time like me @jesec @erossignon. If you find a bug consider opening a PR and fix it, this is what I do when i find one

**Comment by XFaonAE** [comment]
Alright, ill see what I can do

**Comment by XFaonAE** [comment]
@robertsLando One issue is that it uses CJS instead of ESM, and when I make my other libraries the paths are no[t absolute, they are relative. I cant just convert this entire package to support ESM. I'm not exactly sure what to do

**Comment by robertsLando** [comment]
> I cant just convert this entire package to support ESM. I'm not exactly sure what to do

This is our first priority in TODO list, I know @jesec has something in mind for that but feel free to give a try to it. See discussions on: https://github.com/vercel/pkg/pull/1323
