### ISSUE TITLE
pkg --help not command found

### ISSUE THREAD

**Issue by VenPot** [zeit/pkg#270]
i installed  using npm install pkg and  after that pkg is not recognized command is the error messsage i am getting

i am using windows 7 professional

**Comment by reitmaster** [comment]
does `pkg -h` work?

**Comment by VenPot** [comment]
It does not work. I do see it in the node_modules folder but command does not work.
![image](https://user-images.githubusercontent.com/22551591/32019779-449f9f06-b99c-11e7-846f-3cccb600ac62.png)

**Comment by cancerberoSgx** [comment]
is working fine for mi in windows 10 . Did you installed pkg globally?

`npm install -g pkg`

for running locally you can also do it like this: 

```
npm install pkg
node node_modules/pkg/lib-es5/bin.js my/project ....
```

**Comment by VenPot** [comment]
i am using it in linux now.  my app.js takes an file as a parameter .
node app.js filename
how do i package this as an exe ? and where should i place the input file to the exe?

**Comment by cancerberoSgx** [comment]
does the following command work? 

 $ pkg -v

If so - from your last comment , if I understand correctly your app takes a parameter that points to a .js file that is part of your application ? Am I right ? if so that's very strange... I'm not following - explain your problem better

**Comment by VenPot** [comment]
Sure thing, thank you for your time!

Node app.js input.xml

The above works fine. App.js accepts a xml file as the parameter then based
on some logic splits the input.xm to multiple files


When I try to PKG this , how should I pass the input.xml parameter to the
exe?

**Comment by cancerberoSgx** [comment]
no just run 

$ pkg app.js

(no arguments) that will generate three executable - probably app-linux, macos and .exe  

you can then just execute the exec passing all the pararmeters you need : 

$ ./app-linux input.xml

(that would be the same as node app.js input.xml). GOod luck .

**Comment by VenPot** [comment]
I tried that in Windows, did not work. Where should I place the input.xml?
I placed in the same directory as the exe. And ran it from command prompt
It did not work.

**Comment by VenPot** [comment]
Exactly, the xml file is an user input.
When I do node app.js input.xml. it works.

I am doing something wrong in the way I PKG it but not able to figure out
what

**Comment by cancerberoSgx** [comment]
execute pkg app.js and past here the output to see if there is an error. Does it generate the executables ?

**Comment by VenPot** [comment]
![image](https://user-images.githubusercontent.com/22551591/32357580-78cbeebe-c014-11e7-8daf-9d17ddca95a0.png)

executable is there , above is output when i run it

**Comment by cancerberoSgx** [comment]
my guess is that you are hardcoding index.xml in your code instead of reading it from the given file passed in the arguments. I'm compiling the following program with pkg and is running as expected with node and from the executable: 

```
var lastArg = process.argv[process.argv.length-1]
console.log('and te file is : ' +lastArg, require('fs').readFileSync(lastArg).toString())
```

If you read the file usign a hardcoded string instead of the argument then i think pkg will treat it as an asset and in that case you need to package the asset also like explained in the docs: 

"pkg": {
    "assets": "views/**/*"
  }

**Comment by VenPot** [comment]
@cancerberoSgx   you killed it man!  . I was able to get it to work .

**Comment by VenPot** [comment]
unrelated to my issue -  I don't see any competitors  t  in this space,any reason why the downloads for pkg is not high?

**Comment by cancerberoSgx** [comment]
people installs pkg with npm -g not downloading I guess... Can you close the issue then ? thanks

**Comment by VenPot** [comment]
sounds good , thanks again man!

**Comment by unepicgames** [comment]
h
