### ISSUE TITLE
packaged binary does not RPM nicely

### ISSUE THREAD

**Issue by bill-kitsune** [zeit/pkg#293]
It seems that the binary created from pkg does not like to be rpm'd.  I'm not sure which part of the rpming process doesn't jive with it, but I have created a test repo to reproduce the problem.  https://github.com/bill-kitsune/nello

It includes the spec file I am trying to use.  This is the guide I've been following for creating rpms in case that is useful. https://rpm-packaging-guide.github.io/#introduction

# To reproduce

* Run `cp -R nello nello-1.0.0 && tar -cvzf nello-1.0.0.tar.gz`
* Copy spec files and sources to rpmbuild directory (~/rpmbuild/SPECS & ~/rpmbuild/SOURCES) respectively) 
* run `cd ~/rpmbuild && rpmbuild -bb --clean SPECS/nello.spec`
* yum install created RPM
* run `nello`

Expected Output `Hello World`
Actual Output `Pkg: Error reading from file`

**Comment by thedillonb** [comment]
Could you be hitting a binary stripping issue? `rpmbuild` will strip binaries to make space which seems to affect how `pkg` created the executable: http://livecipher.blogspot.com/2012/06/disable-binary-stripping-in-rpmbuild.html

You should be able to disable it via: `%define __os_install_post %{nil}`

**Comment by kumardevendra26** [comment]
@bill-kitsune Are you able to fix this issue? I also stuck at same point. 
When I checked the size of installed binary, It is same as the original one. I don't think so its a stripping issue.

**Comment by bill-kitsune** [comment]
@kumardevendra26 I was able to get this working at least with the test repo I mentioned originally.  It does seem like it was the binary stripping for me anyways.  I needed to get something into the hands of people quickly so I ended up doing something different for installing while I was waiting for an answer so I never ended up trying it with something a little less trivial. 

Try using https://github.com/bill-kitsune/nello as a quick test.  If you can get that to work then I imagine it might be something a little different.

**Comment by zhangguanzhang** [comment]
```
%define __os_install_post %{nil}
```
works for me
