### ISSUE TITLE
ReferenceError: path is not defined

### ISSUE THREAD

**Issue by dunklesToast** [zeit/pkg#319]
Hey!

Since today I noticed a weird behavior in `pkg`. I wanted to build an application but got this error:
`Unhandled promise rejection (rejection id: 2): ReferenceError: path is not defined`
I dont really understand where the error is because Path is a Core module. I am using `pkg@4.3.0-beta.5` on macOS 10.12.6
Packaging is started by `pkg src/Main.js` and when I start the Main.js normally with `node Main.js` everything works.
Hope you can help
- tom

**Comment by j-brown** [comment]
@dunklesToast  do you have resolution on this issue? I'm having the same problem

**Comment by dunklesToast** [comment]
The issue was that somehow I did `require('./path')` which was my mistake.
