### ISSUE TITLE
Getting error "Refusing to overwrite non-file output"

### ISSUE THREAD

**Issue by lemonbuzz** [zeit/pkg#320]
Version: 4.3.0-beta.5 

Trying to compile my app on a Raspberry pi 3 with a fresh rasbian jessie install produces this error.

I have not found this error anywhere else on here...

Any help is appreciated

**Comment by Controlhaus** [comment]
Having the same issue. @lemonbuzz Did you find a way to resolve this?

**Comment by Controlhaus** [comment]
Figured it out. Was doing pkg on app.js and there was also a folder called app. Changing app.js to index.js fixed it.
