### ISSUE TITLE
Raven dynamic import not supported

### ISSUE THREAD

**Issue by pkeuter** [zeit/pkg#343]
https://github.com/getsentry/raven-node/blob/master/lib/instrumentation/instrumentor.js#L37

This is not supported as mentioned in the README. But how do I include these files in the project? I imagine that Raven has to be added to the dictionary, correct?

**Comment by pkeuter** [comment]
This is fixed by including them in the build process

**Comment by brudi95** [comment]
and how do you include them in the build process? is there any option you can pass?
