### ISSUE TITLE
How do i package node_modules

### ISSUE THREAD

**Issue by SevenSinS02** [zeit/pkg#357]
Hi! if the packaged app starts and closes if I don't add the node_modules directory in the same directory as the project.

**Comment by Clement-TS** [comment]
What kind of dependencies do you include within your `node_modules` directory ?
pkg states in the *README* it does not currently include native modules within the bundle:

> Native addons (.node files) use is supported, but packaging .node files inside the executable is not resolved yet. You have to deploy native addons used by your project to the same directory as the executable. 

Another common error is not to non static requires in your node.js code:

```js
// this won't work
const config = require(__dirname + '/config.js')
```

I hope this helps,

**Comment by SevenSinS02** [comment]
Yup! I got it working. I missed the part about the native modules. Apologies for the late update.
