### ISSUE TITLE
Release with github releases

### ISSUE THREAD

**Issue by ksmithut** [zeit/pkg#38]
It would be awesome to set up github releases for the project in order to work well with other package managers (like homebrew and such).

**Comment by igorklopov** [comment]
Can you give an example of such GHR setup? pkg is npm package and requires node.js to run, how do you want to install it via homebrew?

**Comment by arikfr** [comment]
Can't you compile pkg with pkg? :)

**Comment by ksmithut** [comment]
@igorklopov [now-cli](https://github.com/zeit/now-cli) I believe is an example of how this is used, and I believe `pkg` is used to package it (only an assumption, I have no evidence of this). I'm not sure how they set it up, but it made it easy to target the [releases](https://github.com/zeit/now-cli/releases) to install via homebrew.

Homebrew doesn't need to be a release target for this project. I'm fine maintaining my own. One of the reasons I like to use Homebrew (or other package managers) for my global node modules is because I use `nvm` to switch between node versions a lot. I am changing and installing new/old versions of node at least weekly, sometimes daily. If I install global packages via `npm`, they stay with their version of node. So if I happened to switch to a version of node that I haven't install `pkg` or `now` on, I have to reinstall it. There are ways to sync those packages across versions, but it's either a semi-manual process or it installs duplicates, and upgrading one version to the latest doesn't update any of the other installations. I would prefer to install it once, and upgrade it once.

But like I said, this project doesn't need to attempt be compatible with Homebrew, but standard github releases might be nice to enable distribution.

**Comment by leo** [comment]
We'll do this from now on, of course ([here](https://github.com/zeit/pkg/releases))! 😉
