### ISSUE TITLE
Cannot find module 'system'

### ISSUE THREAD

**Issue by qinqin772** [zeit/pkg#385]
i wrote a js script to help my colleague rename a bunch of jpg files with regular name,in this script ,i used module system, just written as 'var fs=require('system')',blablabla,it works good. but i'm trying to make it more firendly ,so i searched a way to compile it into an executable （.exe）file by using pkg，here comes the problem

![image](https://user-images.githubusercontent.com/20991293/37885220-92c5589e-30e6-11e8-85b8-a9184ed5d5be.png)

i checked some issues,but still got no clue,so posted it up,

thanks in advance

**Comment by igorklopov** [comment]
@qinqin772 there is no native module `system` in nodejs. Probably in old versions. Please check if your script works in pure nodejs before compiling with `pkg`.

**Comment by qinqin772** [comment]
when not compling with pkg,run my script in cmd like node 'my script name'  works good,but it comes to error like this when used compiling with pkg
