### ISSUE TITLE
Package Node-Red project

### ISSUE THREAD

**Issue by thomasburf** [zeit/pkg#407]
I'm attempting to run pkg on an express project that contains Node-Red, but when I attempt to run the exe it throws the error "Node-RED not built". Everything runs fine when done locally.

**Comment by iba-jsykes** [comment]
To anyone else looking at using this for node-red, you'll have to do as the readme says and change some require paths to get it to work properly, the error above is more than likely caused by the checkBuild method which cant find red.min.js .

**Comment by spatel626** [comment]
Does anyone have a working package.json file with the correct assets and scripts of pkg for node-red. I am getting the same "Node-RED not built" error when running the exe

**Comment by thomasburf** [comment]
I ended up including the entire node-red* directories and that solved the issue. Not the most efficient practice, but it worked.

**Comment by dheerajaggarwal** [comment]
I have faced the same issue when using the `js-yaml` dependency in my project. More specifically `js-yaml` uses the `esprima` dependency that was causing the issue. 

I am not using the Node-Red project. But I found the same dependency `js-yaml` over here as well so I thought to share this information.
