### ISSUE TITLE
Potential security vulnerability

### ISSUE THREAD

**Issue by wildlifehexagon** [zeit/pkg#409]
I got a notice from GitHub today with the following:

"Known moderate severity security vulnerability detected in hoek < 5.0.3 defined in package-lock.json."

After digging into my dependencies, it looks like this is buried inside an older version of `request`, which is itself inside `pkg-fetch`.

└─┬ pkg@4.3.1
  └─┬ pkg-fetch@2.5.4
    └─┬ request@2.81.0
      └─┬ hawk@3.1.3
        ├─┬ boom@2.10.1
        │ └── hoek@2.16.3  deduped
        ├── hoek@2.16.3 
        └─┬ sntp@1.0.9
          └── hoek@2.16.3  deduped

**Comment by sunnyday90210** [comment]
run npm i hoek on the root of your project then push your updated package-lock.json file this should fix the issue.

**Comment by tingshao** [comment]
Github made a mistake and it has been updated that hoek versions < 4.2.1 have such issue. (see [this](https://github.com/hapijs/hoek/issues/247))
One of our project depends on pkg and we also got such a security notification, is there someone watching this?

**Comment by igorklopov** [comment]
Fixed in latest commits

**Comment by roguedronegithub** [comment]
hi
