### ISSUE TITLE
Project license

### ISSUE THREAD

**Issue by Calinou** [zeit/pkg#41]
I don't see any license attached to this repository; could you please add an open source license (like the MIT license) so we can be sure we can use this legally?

Thanks in advance.

**Comment by mrkmg** [comment]
Seconded. I would love to give this a try as well

**Comment by TooTallNate** [comment]
It's MIT. Closed by https://github.com/zeit/pkg/commit/e93c6e99efa4d6113a983126c2cbe7b8208708b1.
