### ISSUE TITLE
Difference from nexe?

### ISSUE THREAD

**Issue by jondot** [zeit/pkg#42]
Could you highlight in a nutshell how pkg is different?
https://github.com/nexe/nexe

so far i'm seeing Nexe rebuilding node with source, and pkg inlining the source into a new binary (thus not requiring a node rebuild)

Thanks!

**Comment by calebboyd** [comment]
Nexe contributor here. I also built [xbin](https://github.com/calebboyd/xbin) as a response to enclose being closed source. Its great to see it as OSS in pkg!

A short description of how the three projects work. (Please correct me if I missed anything)

[nexe](https://github.com/nexe/nexe): 
 - Bundles your application ala webpack, rollup, browserify etc.
 - Downloads node source
 - Adds your application bundle as a native module
 - applies arbitrary source patches. 
 - Builds node from source
 - Code is run as main when executable is run

[xbin](https://github.com/calebboyd/xbin): 
 - Downloads node source (or a prebuilt binary)
 - Applies arbitrary source patches
 - Adds custom main module to load application code
 - Maybe compiles downloaded source
 - Adds application bundle to the end of the binary
 - Code is read and executed from the end binary when the file is run

[pkg](https://github.com/zeit/pkg):
 - Bundles the application with the v8 script compiler into a snapshot
 - Downloads the node source (or a prebuilt binary)
 - Applies arbitrary source patches
 - Maybe compiles downloaded source
 - Adds snapshotted output to the end of the binary
 - Snapshot (cachedData from v8 (vm.Script) is loaded/run when binary executes.

**Comment by rauchg** [comment]
Thanks for your comparison @calebboyd.

I'll add the following: we've been using `pkg` in production for a year. We decided to open source it because it's remarkably easy to use (just run `pkg`) and it works really well for us. We're glad to contribute to this rich ecosystem and welcome others!

**Comment by rohmanhm** [comment]
How about difference between Node-Compiler https://github.com/pmq20/node-compiler

**Comment by agauniyal** [comment]
@rohmanhm Node-Compiler mentions differences in its readme -
>Pkg hacked fs.* API's dynamically in order to access in-package files, whereas Node.js Compiler leaves them alone and instead works on a deeper level via libsquash. Pkg uses JSON to store in-package files while Node.js Compiler uses the more sophisticated and widely used SquashFS as its data structure.

**Comment by danielo515** [comment]
Thanks everyone that has notted down the differences between all those projects.
Now from an user point of view, which tool is better at what ?  I mean, what kind of projects targets each tool, or what kind of use-cases are better for one or another ?

 regards

**Comment by sebfindling** [comment]
Would also like to know what @danielo515 asked :D

**Comment by Keidrych** [comment]
I've used all 3 tools to create binaries, each has its strength and quirks.

- node-packer/node-compiler/enclose.io is the slowest of all tools to use, it has a great advantage that you can pretty much code however you want and the app will do its best to work it out, but for a continuous release process the compile time is just a killer.

Technologically there are differences between Nexe and Pkg, but one of the features I really like with Pkg is the ability to easily add user code as plugins / modules during run-time and as I work a lot on enterprise applications this extension level is an essential feature.

.node files are just a pain with Pkg though, and yes I've tried quite a few tricks to make them simpler to integrate and manage but as they need to be in the same root as the binary I often find my users forget to include them or complain why there's an addition .node file in the base directory (as they don't care that the binary is written in node) In this sense nexe works well.

Currency is also a challenge at the moment, in that at this time of writing Pkg 8.x stream is 8.9.0 while LTS is 8.11.3 so would be great to see this automatically kept more current (I know we can build from source our-self but ...)

Other big difference for those of us using containers is that Pkg built binaries explode in Alpine Linux, so Debian is the better choice for packaging. While Nexe does support Alpine

Dynamic requires with Pkg can also be more than challenging depending on your application architecture. It took a few passes to make one of our more complex applications find a way to static require our own modules to keep the tree happy.

Pkg is without doubt my first choice for binaries and only fallback to Nexe for the specific reasons mentioned above

**Comment by sebfindling** [comment]
Absolutely agree with @Keidrych. I just finished implementing `pkg` on my app's flow and it took me *days* to find what path to use where, and when. It works flowlessly now, tho.
