### ISSUE TITLE
Determine if app is packaged from within the main process?

### ISSUE THREAD

**Issue by digitalnature** [zeit/pkg#425]
Let's say I need to get the script/app directory,
This would be `path.dirname(process.execPath)` in the packaged app, and `__dirname` in the unpackaged main.js script.
How can I know if the process is running the pkg version or not?

**Comment by kspearrin** [comment]
`if(process.pkg) { /* in pkg */ }`

**Comment by digitalnature** [comment]
cool. thanks :)
