### ISSUE TITLE
Use `start` script

### ISSUE THREAD

**Issue by piranna** [zeit/pkg#43]
The canonical default executable is `start` script in the `package.json` file, that by default is `server.js` file, not `bin` entry since you can define several binaries in a single package.

**Comment by TooTallNate** [comment]
That is, you'd like to just run `pkg` without specifying a filename? An interesting idea. The problem with `start` is that it's an arbitrary shell command, not a JavaScript entry point. The `main` entry point could perhaps be more appropriate since it does point to a JavaScript file.

**Comment by TooTallNate** [comment]
Or some property in the `package.pkg` config object, like `"entrypoint"`.

**Comment by igorklopov** [comment]
You can always specify entry point javascript file explicitly in CLI instead of passing path to `package.json`.

**Comment by JimmyBoh** [comment]
Thoughts on using the [`main`](https://docs.npmjs.com/files/package.json#main) field?

I know it's primarily used in libraries, but it would be a good fit for `pkg` as well.

**Comment by piranna** [comment]
I would still go for the start script entry, also if it's supposed to be a
shell command, because people usually just define an executable there or if
not an ad-hoc executable script can be created. If not, I would add a new
field, but I'm a bit against this idea having currently valid alternatives.

**Comment by igorklopov** [comment]
Sorry, i can not get why you don't like `bin` field. Pkg's purpose i to (mostly) preserve `npm i something -g` tool installation and usage scenario. Since globally installed tool uses `bin` field, the idea behind pkg was to use `bin` field as well.

**Comment by igorklopov** [comment]
And yeah, you can specify several subfields in `bin` field. Pkg will use one that's name matches with `name` field of `package.json`.

**Comment by TooTallNate** [comment]
@igorklopov Ahhh I did not realize that the `bin` entry was already supported. I see now that it's also [documented in the README](https://github.com/zeit/pkg#usage).

I'm closing since I don't think it makes sense to duplicate functionality when there is already a mechanism to specify entry point in the `package.json`. Thank you for the suggestion though!

**Comment by piranna** [comment]
Please open this again, the problem is not the lack of functionality but
the fact it's not standard compliant, as start script is. Please read npm
package.json documentation and fix that, bin field is not designed to be
used that way and it's a bug.

**Comment by TooTallNate** [comment]
@piranna The `"start"` script is used for starting **servers**, _not_ CLI applications. The `bin` field is absolutely used for CLI applications, and npm encourages this with the `--global` flag installing into your `$PATH`.

`pkg` mapping to `bin` is perfect.

**Comment by piranna** [comment]
`npm start` is also used to start cli applications too, I have seen using `server.js` just for this everywhere. Also, since several years ago usage of `--global` and globally installed modules are absolutely deprecated, so that's not the point. You can use `bin`, but that's a mapping of the executables that offer that module, that can be several of them, and there's no requeriment that any of them has the same name of the current module, so blindly trust on that field is a bad usage and a bug according to the spec. As I said before, better alternatives are to use standard `start` script, or if not following standard practices, add a new custom field on `package.json` file just for this.

**Comment by dotcypress** [comment]
Great idea with `npm start` 👍 

Implementing that allows us easily pack [micro-services](https://github.com/zeit/micro) to single executable.

**Comment by joaodvilla** [comment]
Hello, is it possible to run a global CLI, like "adonis migration: run" from pkg side?
