### ISSUE TITLE
New patch release?

### ISSUE THREAD

**Issue by luanpotter** [zeit/pkg#441]
Hi, would it be possible to have a new patch release with the current version on the master branch, just to update `pkg-fetch` from `2.5.4` to `2.5.5`?

It seems that the current `4.3.1` deployed on NPM uses the previous version, which in turn uses a very old `request` version, which now is deprecated and causes warnings due to security issues on the npm audit of several of my projects.

Since it's a very minor change, I'm hoping it's very easy just to drop a new version on the registry. I'm sorry if they are scheduled or if there are more steps in this process, or if this isn't the place to ask, as I'm unaware of it.

**Comment by igorklopov** [comment]
Done!
