### ISSUE TITLE
NPM scripts within PKG

### ISSUE THREAD

**Issue by paulmowat** [zeit/pkg#446]
Is there anyway to run a npm script within pkg?

Use case is i want to run a npm script that processes sequelize migrations before starting my webserver to ensure the database is up to date.

I'm doing something like 

```javascript 
deployAppDependancies()
    // Perform DB migrations and seeders
    .then(() => {
      // Require dbconfig so that the correct .env file is picked up before we try and update any databases and cached.
      require('../config/dbconfig')
      return exec.execSync('npm run prestart', {stdio: 'inherit'})
    })
    // Start Server
    .then(() => {
      require('./www.js')
    })
    .catch((err) => {
      console.log('Error: ' + err)
      process.exit(1)
    })
```

**Comment by paulmowat** [comment]
I figured out a different way to do the above so closing hte log.

**Comment by ikattey** [comment]
@paulmowat, would you mind sharing your solution for this?

I'm also having difficulty running Sequelize migrations from within the packaged binary.

**Comment by paulmowat** [comment]
I was trying to use npm prestart to run the migrations using the sequelize cli. 

I changed approach and used the umzug library to write the migrations programmatically. 

I then build that into my applications start routine which pkg uses to start the application.

Code below. Hope that helps :)

dbUpdater.js
```javascript
var Umzug = require('umzug')
var path = require('path')
var models = require('../../db/models')
var sequelize = models.sequelize

var logger = require('../../lib/log/logger.js')

var env = require('../../config/config').env
var dbconfig = require('../../config/dbconfig')[env]

// config for using Umzug for migrations
var migratorConfig = {
  storage: dbconfig.migrationStorage,
  storageOptions: {
    sequelize: sequelize,
    modelName: 'SequelizeMeta',
    tableName: dbconfig.migrationStorageTableName
  },
  logging: (msg) => {
    logger.info(msg)
  },
  migrations: {
    path: path.join(__dirname, '../../', 'db/migrations'),
    pattern: /^\d+[\w-]+\.js$/,
    wrap: (migrationFn) => {
      return () => {
        return migrationFn(sequelize.queryInterface, sequelize.Sequelize)
      }
    }
  }
}

// config for using Umzug for DB seeding
var seederConfig = {
  storage: dbconfig.seederStorage,
  storageOptions: {
    sequelize: sequelize,
    modelName: 'SequelizeData',
    tableName: dbconfig.seederStorageTableName
  },
  logging: (msg) => {
    logger.info(msg)
  },
  migrations: {
    path: path.join(__dirname, '../../', 'db/seeders'),
    pattern: /^\d+[\w-]+\.js$/,
    wrap: (migrationFn) => {
      return () => {
        return migrationFn(sequelize.queryInterface)
      }
    }
  }
}

var migrator = new Umzug(migratorConfig)
var seeder = new Umzug(seederConfig)

function retryDBConnect (resolve, reject, context, maxTries) {
  sequelize.authenticate()
    .then(() => {
      logger.info('Database Connected')
      resolve()
    },
    function (err) {
      if (maxTries < 0) {
        logger.error('Sequelize reached max tries to connect. FAIL.')
        reject(err)
      } else {
        setTimeout(function () {
          logger.debug('Not connected to the DB, trying again in 2 seconds')
          retryDBConnect(resolve, reject, context, maxTries - 1)
        }, 2000)
      }
    })
}

function tryDBConnect () {
  return new Promise(function (resolve, reject) {
    retryDBConnect(resolve, reject, null, 10)
  })
}

// expose one instance of Umzug for both migrator and seeder.
// this means we have migrator.up().then...
// as well as seeder.up().then...
module.exports = {
  migrator,
  seeder,
  tryDBConnect
}
```

relevant part of start.js
```javascript
 // Deploy application dependancies.
  deployAppDependancies()
    // Perform DB migrations and seeders
    .then(() => {
      return dbUpdater.tryDBConnect()
    })
    .then(() => {
      return dbUpdater.migrator.up()
    })
    .then(() => {
      return dbUpdater.seeder.up()
    })
    // Start Server
    .then(() => {
      require('./www.js')
    })
    .catch((err) => {
      console.log('Error: ' + err)
      process.exit(1)
    })
```

**Comment by ikattey** [comment]
> I was trying to use npm prestart to run the migrations using the sequelize cli.
> 
> I changed approach and used the umzug library to write the migrations programmatically.
> 
> I then build that into my applications start routine which pkg uses to start the application.
> 
> Code below. Hope that helps :)
> 
> dbUpdater.js
> 
> ```js
> var Umzug = require('umzug')
> var path = require('path')
> var models = require('../../db/models')
> var sequelize = models.sequelize
> 
> var logger = require('../../lib/log/logger.js')
> 
> var env = require('../../config/config').env
> var dbconfig = require('../../config/dbconfig')[env]
> 
> // config for using Umzug for migrations
> var migratorConfig = {
>   storage: dbconfig.migrationStorage,
>   storageOptions: {
>     sequelize: sequelize,
>     modelName: 'SequelizeMeta',
>     tableName: dbconfig.migrationStorageTableName
>   },
>   logging: (msg) => {
>     logger.info(msg)
>   },
>   migrations: {
>     path: path.join(__dirname, '../../', 'db/migrations'),
>     pattern: /^\d+[\w-]+\.js$/,
>     wrap: (migrationFn) => {
>       return () => {
>         return migrationFn(sequelize.queryInterface, sequelize.Sequelize)
>       }
>     }
>   }
> }
> 
> // config for using Umzug for DB seeding
> var seederConfig = {
>   storage: dbconfig.seederStorage,
>   storageOptions: {
>     sequelize: sequelize,
>     modelName: 'SequelizeData',
>     tableName: dbconfig.seederStorageTableName
>   },
>   logging: (msg) => {
>     logger.info(msg)
>   },
>   migrations: {
>     path: path.join(__dirname, '../../', 'db/seeders'),
>     pattern: /^\d+[\w-]+\.js$/,
>     wrap: (migrationFn) => {
>       return () => {
>         return migrationFn(sequelize.queryInterface)
>       }
>     }
>   }
> }
> 
> var migrator = new Umzug(migratorConfig)
> var seeder = new Umzug(seederConfig)
> 
> function retryDBConnect (resolve, reject, context, maxTries) {
>   sequelize.authenticate()
>     .then(() => {
>       logger.info('Database Connected')
>       resolve()
>     },
>     function (err) {
>       if (maxTries < 0) {
>         logger.error('Sequelize reached max tries to connect. FAIL.')
>         reject(err)
>       } else {
>         setTimeout(function () {
>           logger.debug('Not connected to the DB, trying again in 2 seconds')
>           retryDBConnect(resolve, reject, context, maxTries - 1)
>         }, 2000)
>       }
>     })
> }
> 
> function tryDBConnect () {
>   return new Promise(function (resolve, reject) {
>     retryDBConnect(resolve, reject, null, 10)
>   })
> }
> 
> // expose one instance of Umzug for both migrator and seeder.
> // this means we have migrator.up().then...
> // as well as seeder.up().then...
> module.exports = {
>   migrator,
>   seeder,
>   tryDBConnect
> }
> ```
> 
> relevant part of start.js
> 
> ```js
>  // Deploy application dependancies.
>   deployAppDependancies()
>     // Perform DB migrations and seeders
>     .then(() => {
>       return dbUpdater.tryDBConnect()
>     })
>     .then(() => {
>       return dbUpdater.migrator.up()
>     })
>     .then(() => {
>       return dbUpdater.seeder.up()
>     })
>     // Start Server
>     .then(() => {
>       require('./www.js')
>     })
>     .catch((err) => {
>       console.log('Error: ' + err)
>       process.exit(1)
>     })
> ```

Awesome, thanks!

I'll try this out.

**Comment by psaxena** [comment]
> Is there anyway to run a npm script within pkg?
> 
> Use case is i want to run a npm script that processes sequelize migrations before starting my webserver to ensure the database is up to date.
> 
> I'm doing something like
> 
> ```js
> deployAppDependancies()
>     // Perform DB migrations and seeders
>     .then(() => {
>       // Require dbconfig so that the correct .env file is picked up before we try and update any databases and cached.
>       require('../config/dbconfig')
>       return exec.execSync('npm run prestart', {stdio: 'inherit'})
>     })
>     // Start Server
>     .then(() => {
>       require('./www.js')
>     })
>     .catch((err) => {
>       console.log('Error: ' + err)
>       process.exit(1)
>     })
> ```

Hi, 

Your post helped to let know how to get migrations running before server start. I am trying your first wayout of running migrations in prestart script. But i am getting "'sequelize' is not recognized as an internal or external command" error. I've copied "node_sqlite3.node" in same dir compiled binary of application. 

Want to check with you how did you get this working or can suggest some resolution to this issue?

Thanks,
Pooja
