### ISSUE TITLE
--targets should allow specifying build options more flexibly and intelligently

### ISSUE THREAD

**Issue by grempe** [zeit/pkg#45]
It would be nice to be able to specify that you want *all* targets built that your current system is capable of building.

**Comment by phoikoi** [comment]
I'm not sure that would be as useful as it might seem at first glance... would that include every possible version of node as well, for all platforms, on every architecture?  Perhaps something like `node7-[mac,linux]-*` could be used, and only compatible architectures would be built (such as only x64 for macos, but x86, x64, armv6, armv7 for linux).  Just a thought.

**Comment by grempe** [comment]
Yes, I agree that the style @phoikoi  proposed is likely a better idea. 👍 I'll rename this issue.

**Comment by igorklopov** [comment]
Does specifying `-t node7-macos,node7-linux` solves you problem? I see no difference, except no need to implement and maintain `[]` parser 🙂

**Comment by grempe** [comment]
Yes, just not as concisely. I guess the ideal is to be able to use a wildcard for any portion of the node-platform-arch settings and have the system just be able to calculate which are possible to build on the current host that meet those criteria. And only attempt to build those.

**Comment by igorklopov** [comment]
https://github.com/zeit/pkg/issues/145
`--no-bytecode` adds an ability to create binaries for ANY target from ANY host. So, lets keep targets list explicit.
