### ISSUE TITLE
pkg with sqllite

### ISSUE THREAD

**Issue by dashng** [zeit/pkg#463]
Hi, 
I need to create a web tool with sequelize sqllite.

The package json below:

```
{
  "name": "pkg_test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "bin": "app.js",
  "pkg": {
    "assets": [
      "assets/**/*"
    ],
    "scripts": ["src/**/*.js", "node_modeules/**/*"]
  },
  "author": "gsp-dalian-ued@csico.com",
  "license": "ISC",
  "dependencies": {
    "express": "^4.16.3",
    "sequelize": "^4.38.0",
    "sqlite3": "^4.0.1"
  }
}
```
I created the sqllite database file and location the file to "assets/html/database.sqllite‘.

```
const path = require('path');
const Sequelize = require('sequelize');
console.log(path.join(__dirname, '../../', 'assets/html/database.sqlite'));
const sequelize = new Sequelize('database', 'username', 'password', {
  host: 'localhost',
  dialect: 'sqlite',
  pool: {
    max: 5,
    min: 0,
    idle: 10000
  },
  storage: path.join(__dirname, '../../', 'assets/html/database.sqlite')
});

module.exports = sequelize;
```

After package the web app to .exe file, exec the exe file a error message shown below.

```
Unhandled rejection SequelizeConnectionError: SQLITE_CANTOPEN: unable to open database file
    at Database.AbstractConnectionManager.getConnection.Promise.connections.(anonymous function).lib.Database.err (/snapshot/cnt-tool/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:66:63)

```
Any help would be appreciated.

Thanks.

**Comment by AxelTerizaki** [comment]
I'm not sure if you can modify files inside the snapshot/exe. Have you tried having the database outside?

**Comment by kauffmanes** [comment]
@dashng I don't know if this would cause your issue, but it looks like `node_modules` is spelled incorrectly in your package.json pkg assets.

And the storage line: `storage: path.join(__dirname, '../../', 'assets/html/database.sqlite')` has three arguments, and the pkg docs says it should have two. Again, I don't know if that would cause your issue but it might be worth a shot...

> "When pkg encounters path.join(__dirname, '../path/to/asset'), it automatically packages the file specified as an asset. See Assets. Pay attention that path.join must have two arguments and the last one must be a string literal."

[https://github.com/zeit/pkg#detecting-assets-in-source-code](https://github.com/zeit/pkg#detecting-assets-in-source-code)

If those aren't causing your issues, let me know if you solved it because I also have this error message!

**Comment by jpadilla** [comment]
I'm running into this same error using sqlite3 directly. File does exist inside snapshot and I'm only trying to open as readonly.

```
    let dbPath = path.join(__dirname, 'db.sqlite');
    this.db = new sqlite3.Database(dbPath, sqlite3.OPEN_READONLY, (err) => {
      console.log(fs.existsSync(dbPath));
      console.log(err);
    });
```

```
true
{ [Error: SQLITE_CANTOPEN: unable to open database file] errno: 14, code: 'SQLITE_CANTOPEN' }
```

Any ideas?
