### ISSUE TITLE
'pkg' binary name conflict

### ISSUE THREAD

**Issue by myfreeweb** [zeit/pkg#47]
Hi!

I'm currently looking at various node packagers, and it's very nice to see that yours supports FreeBSD (unlike [nar](https://github.com/h2non/nar) which only supports building executables for Linux, Darwin and Solaris — the ones with node binaries published by the node project itself).

However… FreeBSD's native package manager is literally called `pkg` ;)

**Comment by rauchg** [comment]
This also happened to `node`, which conflicted in certain Linux distributions, that just proceeded to distribute it as `nodejs`.

I would expect Freebsd to do the same: distribute it as `pkgjs` or have people install it as such (e will include instructions for how to do this in the README).

The bottom line is that in 10 years you will hardly find a name that is short, good, descriptive of your project's goals and doesn't exist already in some `$PATH`. The solution to it is not really complicated for FreeBSD users, so I don't think we will be renaming the project.

**Comment by MareoRaft** [comment]
myfreeweb meant "SunOS", not "Solaris".  SunOS is supported by nar, Solaris is not.

**Comment by myfreeweb** [comment]
@MareoRaft the actual SunOS (<=4.x) died in 1994. Solaris and Illumos have uname "SunOS" for historical reasons (Solaris was SunOS 5.x)
