### ISSUE TITLE
--loglevel param

### ISSUE THREAD

**Issue by simast** [zeit/pkg#48]
Old enclose had `--loglevel` param where you could have disabled warning level log messages for example. I can't seem to find this in the new version. Was it removed for some reason?

In some places I am not using string literals with `require` calls, but including those files using scripts config option. Hence those warnings aren't really interesting to me and I am well aware of the functionality.

**Comment by igorklopov** [comment]
Hi, Simas! I discourage you disable all warnings, because newly introduced bug may come unnoticed. If you really want to mute them, provide `may-exclude` per occurence.
https://github.com/zeit/now-cli/blob/5.0.0/bin/now.js#L114
I will add `may-exculde` description soon to readme.

**Comment by simast** [comment]
Hi Igor!

Thanks for bringing enclose back from the dead (and with Node 7+ support)!

I can's say I am a huge fan of extending and monkey-patching built-in `require` with such a custom functionality and adding pkg specific arguments all over your codebase just to ignore those warnings. There is also an issue that at some point Node.js will decide to implement their own second `require` param for some reason.

Anyway, if you think there is a good reason not to include `loglevel` param - I will have to live with those warnings.

**Comment by igorklopov** [comment]
Is it your code that causes warnings? Or code of npm dependencies? If so, name those npm deps please.

**Comment by simast** [comment]
Yes, my code is causing those warnings. Think about functionality that would load all .js files in a directory (plugins and such).
