### ISSUE TITLE
Error! self signed certificate in certificate chain

### ISSUE THREAD

**Issue by Araknos** [zeit/pkg#490]
Hey,
I'm trying to use pkg with a nodejs app (node v10) but I'm getting an error when running pkg main.js:
`> pkg@4.3.3
> Targets not specified. Assuming:
  node10-linux-x64, node10-macos-x64, node10-win-x64
> Fetching base Node.js binaries to PKG_CACHE_PATH
  fetched-v10.4.1-linux-x64    [                    ] 0%
> Error! self signed certificate in certificate chain
> Asset not found by direct link:
  {"tag":"v2.5","name":"uploaded-v2.5-node-v10.4.1-linux-x64"}
  fetched-v10.4.1-linux-x64    [                    ] 0%
> Error! self signed certificate in certificate chain`

(I tried with @4.3.1 too). Any idea ?

**Comment by Araknos** [comment]
Ok it was due to a proxy !

**Comment by kevin3747118** [comment]
hi @Araknos 
How do u solve proxy issue due to self signed certificate in certificate chain ?

**Comment by Araknos** [comment]
Hi !
Use another connection or ask your IT to review the proxy...
I opted for the first option.

**Comment by raymondsiu** [comment]
Solved by setting this environment variable:
`NODE_TLS_REJECT_UNAUTHORIZED=0`
Thanks corporate proxies for making our lives 50% more difficult.
