### ISSUE TITLE
Using external not compiled js scripts?

### ISSUE THREAD

**Issue by serzhiio** [zeit/pkg#505]
Is it possible to use not compiled js scripts when main compiled binary is running?
As example i want one script to remain changable and dynamically reloaded during work of the main process.

**Comment by serzhiio** [comment]
I'm getting this error:
`Error: File or directory '/**/Capitalist/conf/settings.tpl.js' was not included into executable at compilation stage. Please recompile adding it as asset or script.`
Is it possible to leave this file as is and compile it on runtime?

**Comment by jingsam** [comment]
Please use dynamic require external scripts. For example:
```
require(process.cwd() + './path/to/script.js')
```

**Comment by serzhiio** [comment]
Thank you very much! It helped!
