### ISSUE TITLE
Incorrect project description

### ISSUE THREAD

**Issue by rynmng** [zeit/pkg#51]
Apologies if this is the wrong place to post this, but I couldn't find a more relevant repo.

I was browsing your site and came across this:

![pkg](https://cloud.githubusercontent.com/assets/144899/25594092/3e1560ac-2e8d-11e7-93a2-9c44c59755ba.jpg)

This reads "Singe-Command compiler" instead of the newer description "Package your Node.js project into an executable".

I cloned https://github.com/zeit/github-projects and verified that the latest description is coming through. Just wanted to let you know you may want to refresh your cache, if this is still powering your OSS page.

**Comment by timneutkens** [comment]
This will be fixed with the next release of the website 👌

**Comment by rynmng** [comment]
👍
