### ISSUE TITLE
Getting 500 Error when trying to install

### ISSUE THREAD

**Issue by faridhajnal** [zeit/pkg#533]
Hello, when I run

_npm i -g pkg_

I get the following output : **500 Internal Server Error: @nodelib/fs.stat@^1.0.1**

To be honest,  I am not that level of an expert on NodeJS. And I tried to do it as administrator, same issue.
I have Node 8.11.2 installed on my Windows 10 (x64 OS) machine.

Any help is much appreciated

**Comment by ZQun** [comment]
@faridhajnal Has your @nodelib packaging problem been solved? I had the same problem.
