### ISSUE TITLE
Force module inclusion?

### ISSUE THREAD

**Issue by rraallvv** [zeit/pkg#536]
Is there a way to force the inclusion of two modules that are required conditional like so:

    var foo = require(someCondition ? "module1" : "module2");

**Comment by fisch3r** [comment]
Why not simply require both? Like:
`var module1 = require('module1');
var module2 = require('module2);
var foo = someCondition ? module1 : module2;`

**Comment by rraallvv** [comment]
@fisch3r Thanks. I'll give it a try.
