### ISSUE TITLE
Config property for target needed

### ISSUE THREAD

**Issue by leo** [zeit/pkg#54]
We need to avoid [this](https://github.com/zeit/now-cli/blob/c1ba650ec44576ba3fc1c27fda713d594d8e3867/package.json#L16) using a config property within `package.json` (should hold an array of targets).

**Comment by leo** [comment]
😍❤️

**Comment by leo** [comment]
Would be great if you could introduce that to now-cli once the pkg update is out.

**Comment by igorklopov** [comment]
Done! https://github.com/zeit/now-cli/pull/503

**Comment by leo** [comment]
Wonderful, thanks!
