### ISSUE TITLE
Read file outside exe

### ISSUE THREAD

**Issue by arrazymuhammad** [zeit/pkg#546]
Hello, 

can I read pdf file outside the snapshot? 
is that possible?

thanks.

**Comment by tracker1** [comment]
you should be able to launch a process to do that... regarding PDF specifically, however you may want to just embed pdf.js, which is what chome and firefox both use for PDF viewing.

**Comment by pionl** [comment]
Sure, there is documentation about file paths in readme.

This code will build basePath based on location of the script.

```
const path = require('path')
// Are we running app locally via node?
const isLocal = typeof process.pkg === 'undefined'

// Build the base path based on current running mode (if packaged, we need the location of executable)
const basePath = isLocal ? process.cwd() : path.dirname(process.execPath)
```

**Comment by arrazymuhammad** [comment]
thanks All, everything work fine now.

**Comment by chandru89new** [comment]
@pio

> Sure, there is documentation about file paths in readme.
> 
> This code will build basePath based on location of the script.
> 
> ```
> const path = require('path')
> // Are we running app locally via node?
> const isLocal = typeof process.pkg === 'undefined'
> 
> // Build the base path based on current running mode (if packaged, we need the location of executable)
> const basePath = isLocal ? process.cwd() : path.dirname(process.execPath)
> ```

Thanks a lot. I missed the quotes in the 'undefined' and was wondering why this wasnt working when `process.pkg` was indeed `undefined`.

**Comment by lucky51** [comment]
👍
