### ISSUE TITLE
Dealing with embedded database ?

### ISSUE THREAD

**Issue by udithv** [zeit/pkg#553]
I am working on an simple command line app that uses embedded database like nedb and leveldb. 

the import statement is as follows:

const path = require('path');
const mainDir = process.execPath;

const NAME_DATABASE_PATH = path.join(mainDir, '/db/names.db');
const USER_DATABASE_PATH = path.join(mainDir, '/db/user');

const namesdb = new Datastore({ filename: COMMAND_DATABASE_PATH , autoload: true });
const userdb = levelup(leveldown(USER_DATABASE_PATH));

using them as assets as below is not working.

"pkg": {
    "assets": [
      "./db/names.db",
      "./db/user"
    ]
  },

**Comment by m-onz** [comment]
normally you can store things in the system temo dir:

```js
var os = require('os')

console.log(os.tmpdir())

```

This is because the app will have permission to write the database there and it will persist between app launches and system reboots.

**Comment by udithv** [comment]
@m-onz 
This is great solution. But a database like level already expects a database directory. so after compilation it throws an error on the first run. Is there a way around it?

**Comment by m-onz** [comment]
I'm not sure what the exact compilation error you are running into it. There should be no reason you can't instantiate levelDB inside the temp directory. You might need to check if it already exists first before creating it. I haven't tested the code below... but I think something like this should work.

```js
var os = require('os')
var path = require('path')
var tmp = os.tmpdir()
var leveldb = require('leveldb');
leveldb.open(${path.normalize(tmp+'/demo.db')}, { create_if_missing: true }, onOpen);
```

The only other thing I can suggest is possible spawning a new process to do this kind of stuff.

**Comment by udithv** [comment]
You sir, are a godsend..Thank you solved the issues....
