### ISSUE TITLE
Source code is visible in compiled binary

### ISSUE THREAD

**Issue by amirker** [zeit/pkg#561]
To reproduce:
1. Prepare an executable
2. Open binary in text editor
3. Search for a code line from your source code
=> entire source code is available as plain text

I'm targeting "node8-win-x64"
I have checked it briefly with other platforms as well and it seems to be the same

**Comment by raelmiu** [comment]
Same issue. Don't think it's all the code though. Only node modules, or possibly even the non-production node modules.

**Comment by sstativa** [comment]
Check #190 
It worked for me really well.

**Comment by amirker** [comment]
Thanks sstativa!
All working well now

**Comment by raelmiu** [comment]
Tried out #190 ,  didn't solve my problem at all. Not using a "licence" but if the sub modules have licences maybe that would explain why they are in plain text. Could that be the case?

**Comment by sstativa** [comment]
Usually, I have no problems if all my modules are in `node_modules`.

However, I had an issue recently. One of my modules was set as a `file:./` in the list of dependencies. 
I managed to hide the source code only after deleting the `license` property for this module.
