### ISSUE TITLE
fs.readFile with encoding option can't access files in /snapshot

### ISSUE THREAD

**Issue by vinebrancho** [zeit/pkg#57]
Hi, all.

I think that zeit's pkg is cool solution to everyone who want to simplify their nodejs resources to one executable.
Thanks for efforts of pkg maintainers in zeit :)

I found `fs.readFile` with `{ encoding: 'utf8' }` as options can't read anything in /snapshot, but 
but in `fs.readFile` with only `"utf8"` string as options, there is not such a problem.
It seems that in executable, `fs.readFile` does not handle `encoding` attribute in option of object type. 

Interestingly, `fs.readFileSync` works well in both case. 

The following is test code.
```javascript
const path = require('path')
const fs = require('fs')

const meta = path.join(__dirname, './meta.txt')

let syncdata = fs.readFileSync(meta, { encoding: 'utf8' })
console.log('readFileSync case with { encoding: \'utf8\'} option: ', syncdata)

syncdata = fs.readFileSync(meta, 'utf8')
console.log('readFileSync case with \'utf8\' option: ', syncdata)

fs.readFile(meta, { encoding: 'utf8' }, (err, data) => {
  if (err) {
    console.log(err)
    return 
  }
  console.log('readFile case with { encoding: \'utf8\'} option: ', data)
})

fs.readFile(meta, 'utf8', (err, data) => {
  if (err) {
    console.log(err)
    return 
  }
  console.log('readFile case with \'utf8\' option: ', data)
})
```
the result is the following.
>readFileSync case with { encoding: 'utf8'} option:  # this is test text
>readFileSync case with 'utf8' option:  # this is test text
>readFile case with 'utf8' option:  # this is test text
>{ Error: ENOENT: no such file or directory, open '/snapshot/home/nemoux/nemosnow/snow-apps/pkgsnapshot-test/meta.txt'
>  errno: -2,
>  code: 'ENOENT',
>  syscall: 'open',
>  path: '/snapshot/home/nemoux/nemosnow/snow-apps/pkgsnapshot-test/meta.txt' }

I executed the following command after extracting the following.
> $ pkg index.js -t latest-linux-x64

[pkgsnapshot-test.zip](https://github.com/zeit/pkg/files/972230/pkgsnapshot-test.zip)

Is it a bug or right behavior?

**Comment by igorklopov** [comment]
fixed by https://github.com/zeit/pkg/commit/c0dd2542ec964e81993e2c9b5864e645598a84e1
