### ISSUE TITLE
Pkg: 'callsites' package is temporarily unsupported

### ISSUE THREAD

**Issue by devinivy** [zeit/pkg#58]
I packaged my project, and ran into an issue that inhibits me from successfully running the output binary.  One package I use heavily relies on `parent-module`, which in turn uses `callsites`, which is what causes the error.  Honestly, I was going to be very impressed if it was able to deal with the `parent-module` module :).  Here's the error I get when running the binary.

```
$ pkg --targets node6-macos-x64 .
... Packages, with some "Cannot resolve" warnings which I've added to `scripts` ...

$ ./my-project-macos
/snapshot/my-project/node_modules/callsites/index.js:1
(function (exports, require, module, __filename, __dirname) { module.exports = function() {throw new Error("Pkg: 'callsites' package is temporarily unsupported. Please create a github issue.")};
                                                                                                 ^

Error: Pkg: 'callsites' package is temporarily unsupported. Please create a github issue.
    at module.exports (/snapshot/my-project/node_modules/callsites/index.js:1:98)
    at module.exports (/snapshot/my-project/node_modules/parent-module/index.js:5:15)
    at Object.exports.using (/snapshot/my-project/node_modules/haute-couture/lib/index.js:19:39)
    at Object.console./snapshot/my-project/lib/index.js.dev (evalmachine.<anonymous>:0)
    at Module._compile (evalmachine.<anonymous>:0)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
```

It instructed me to make a github issue, so here I am!  Let me know if I can be useful to help solve the issue, or if I can provide any more information.  Thanks!

**Comment by igorklopov** [comment]
Temporarily fixed with https://github.com/zeit/pkg/commit/d94d3ad5a8424558c5ce2f911665f8ea3e861b39
Please try again and give feedback on how it behaves in your project.

**Comment by devinivy** [comment]
I get a new error now, completely particular to my app, because the output of `parent-module` is `"evalmachine.<anonymous>"`, which isn't what is expected.  If it were able to return the filename within the snapshot, I wonder if that would work.  When I get a moment I'll see if I can get some feedback more specific to the `callsites` issue.

**Comment by igorklopov** [comment]
To be solved by pkg@3.1

**Comment by igorklopov** [comment]
Solved by https://github.com/zeit/pkg/commit/58015f725daa65ae8f357eebf9a4d97b1fda044e
Please wait for `discrete-payload` branch to land

**Comment by devinivy** [comment]
I'll be on the lookout!

**Comment by igorklopov** [comment]
Fixed in `master` branch.

**Comment by devinivy** [comment]
I can confirm the fix works 👍  thank you!
