### ISSUE TITLE
How to run .exe hidden or in system tray?

### ISSUE THREAD

**Issue by jakobrosenberg** [zeit/pkg#585]
Is this possible?

**Comment by aapablaza** [comment]
This is a question. Shouldn't be marked as an Issue.

You could use another program to run a .exe hidden.

For example, here they list 8 possible ways to do that:
https://www.raymond.cc/blog/stealth-or-hide-running-program-from-appearing-in-taskbar-or-traybar/

**Comment by jakobrosenberg** [comment]
Thanks for the feedback.

For anyone else bumping into this issue, this is what I ended up going with.
''PowerShell.exe -windowstyle hidden my-app.exe''
