### ISSUE TITLE
Packaging with npm serialport not including @serialport packages

### ISSUE THREAD

**Issue by SVVijay1205** [zeit/pkg#598]
Hi

I am trying to package using npm serialport and its dependencies are starting with @serialxxx. I do not see any issues in the build or warnings. However, during execution of the package it fails with below message. Am I missing anything to be included while packaging? And this is the command I use 'pkg -t node10-linux-armv7 ./bin/projectname' 

Appreciate your help, Thanks in advance.

Thanks & Regards
Sudhakar Kandasamy

Could not locate the bindings file. Tried:
 → /snapshot/projectname/node_modules/@serialport/bindings/build/bindings.node
 → /snapshot/projectname/node_modules/@serialport/bindings/build/Debug/bindings.node
 → /snapshot/projectname/node_modules/@serialport/bindings/build/Release/bindings.node
 → /snapshot/projectname/node_modules/@serialport/bindings/out/Debug/bindings.node
 → /snapshot/projectname/node_modules/@serialport/bindings/Debug/bindings.node
 → /snapshot/projectname/node_modules/@serialport/bindings/out/Release/bindings.node
 → /snapshot/projectname/node_modules/@serialport/bindings/Release/bindings.node
 → /snapshot/projectname/node_modules/@serialport/bindings/build/default/bindings.node
 → /snapshot/projectname/node_modules/@serialport/bindings/compiled/10.4.1/linux/arm/bindings.node

**Comment by SVVijay1205** [comment]
Closing as it is a duplicate and having a resolution @ Native addons in the documentation. Sorry about it.

**Comment by EscolanoGarnica** [comment]
@SVVijay1205 are you solved this issue?

**Comment by SVVijay1205** [comment]
Hi

 

Yes the issue is resolved by having the “bindings.node” file where the executable is placed.

 

If there is a better solution please let know.

 

Thanks & Regards

Sudhakar Kandasamy
