### ISSUE TITLE
build node fail with error "Error! TypeError: Path must be a string. Received undefined"

### ISSUE THREAD

**Issue by iotblue** [zeit/pkg#604]
https://github.com/zeit/pkg/blob/42946d5e6094f7ed19dc9191bbfa1baadc5b0c34/package.json#L38

new version of globby @ 8.0.2 has been release to resolve compatibility issue with dir-glob and thats lead to break buliding CI packages 

`"globby": "8.0.2",`

**Comment by Trikolon** [comment]
#603

**Comment by igorklopov** [comment]
Fixed in `pkg@4.3.6`. Thanks!
