### ISSUE TITLE
Class.toString() returns incorrect value

### ISSUE THREAD

**Issue by devinivy** [zeit/pkg#62]
When I have a plain JS class and try to turn it into a string, my program hangs.  I'm on a Mac, on node v6.  I think the demo below will provide enough information to get started.

**Contents of test.js**
```js
'use strict';

const arrow = () => null;
const Class = class {};

console.log('arrow');
console.log(typeof arrow);
console.log(arrow);
console.log(arrow.toString());

console.log('Class');
console.log(typeof Class);
console.log(Class);
console.log(Class.toString());

console.log('end');
```

**Demo**
```
$ pkg --targets node6-macos-x64 test.js

$ ./test 
arrow
function
[Function: arrow]
function arrow() { [native code] }
Class
function
[Function: Class]
^C # Program hung here!

$ node -v
v6.4.0

$ node test.js
arrow
function
[Function]
() => null
Class
function
[Function]
class {}
end
```

**Comment by igorklopov** [comment]
Will be eventually fixed by https://github.com/zeit/pkg-fetch/commit/85ce383f1cdf0d0374af316772a233ea573ed391 released.

**Comment by devinivy** [comment]
Out of curiosity, will that require using node v7 with pkg?

**Comment by igorklopov** [comment]
No, it will be backported to all supported versions of Node.js.

**Comment by devinivy** [comment]
Hey @igorklopov I'm finding that this fix doesn't quite follow spec.  While `Class.toString()` no longer errors, it returns a slightly incorrect value.  Should I open a new issue for this?

```js
const A = class {};
console.log(A.toString());
// Outputs : "function A() { [native code] }"
// Expected: "class {}"
```

For more details on the spec, see https://stackoverflow.com/a/30760236.

**Comment by igorklopov** [comment]
Agreed. Reopening and renaming (to keep valuable conversation).
