### ISSUE TITLE
pkg can't work with zeromq module and grpc module

### ISSUE THREAD

**Issue by goforward01** [zeit/pkg#64]
I use zeromq and grpc module in my project, while I tried to use **pkg** to bundle my project, it gave the warning like below:
```
> Warning Cannot resolve 'binding_path'
  /home//test/jzver/node_modules/grpc/src/node/src/grpc_extension.js
  Use a string literal as argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
> Warning Cannot include native addon into executable.
  /hometest/jzver/node_modules/zeromq/build/Release/zmq.node
  The addon file must be distributed with executable.
```
The grpc_extension.js looks like:
```
var binary = require('node-pre-gyp/lib/pre-binding');
var path = require('path');
var binding_path =
    binary.find(path.resolve(path.join(__dirname, '../../../package.json')));
var binding = require(binding_path);

module.exports = binding;
```
  While the grpc module should be compile to node C++ addon with the grpc_extension.js,  and to the zeromq module,  when the compile job is done, it produce the zmq.node to be used in node project. I don't know how to handle node modules like these by **pkg**. 
And my node version is:  6.10.0
  I used the command like this:  pkg -t node6-linux ./server/index.js
  Thanks for amazing work with **pkg**

**Comment by firrae** [comment]
The error you see with grcp is the same one both Socket.io and bcrypt throw as well. I'm trying to sort out the issue as this is the only blocking one for myself currently.

```
> Warning Cannot resolve 'binding_path'
  /Users/steven.lambe/iot/node_modules/bcrypt/bcrypt.js
  Use a string literal as argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
> Warning Cannot resolve 'this.wsEngine'
  /Users/steven.lambe/iot/node_modules/engine.io/lib/server.js
  Use a string literal as argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
```

**Comment by firrae** [comment]
To follow up on this, I've tried the following in my package.json file to no success:

```
"pkg": {
    "scripts": [
        "./node_modules/bcrypt/bcrypt.js",
        "./node_modules/engine.io/lib/server.js"
    ]
  }
```

In the readme it sounds like this is what is being asked for, but I continue to get the issues after adding them as such. As I stated previously, this is the only blocking issue for my project right now if someone can point out what I am missing.

**Comment by igorklopov** [comment]
Please try again with `pkg@3.0.3` but be aware that you must deploy your `.node` files along with executable. https://github.com/zeit/pkg#native-addons

**Comment by firrae** [comment]
OK, everything works for me now, this is sexy...

**Comment by ydubois-fr** [comment]
Hi firrae,
can you explain how you resolve your problem ?
Thanks

**Comment by firrae** [comment]
@ydubois-fr I dug into the node_modules folder and found each module's .node file that it generated and put it in the root directory beside the generated executable. Note that these .node files are native to the platform they were created on.

**Comment by ydubois-fr** [comment]
**@firrae** 
Thanks for your help.
I have the same problem that you with socket.io :
Warning Cannot resolve 'this.wsEngine'
  D:\test\node_modules\engine.io\lib\server.js
  Use a string literal as argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.

I copy the file "server.js" beside the generated executable.....no result.
What file did you copy next to the executable ? (server.js ? the folder "engine.io" ?)

**Comment by firrae** [comment]
@ydubois-fr hmm, I didn't need to copy anything for Socket.io after upgrading to pkg@3.0.3. Can you fill me in on what OS you are on and copy any log you get here? That might help identify what the issue might be.

**Comment by ydubois-fr** [comment]
**@firrae** my node version is v7.10.0, my pkg version is 3.0.3. My OS is windows 10.
I reinstall all my node modules.
I have the warning message when i compile my file.
When i launch my generated executable, all is ok but when i try to communicate with the browser, nothing....socket.io don't work.
Thanks for your help
[view.zip](https://github.com/zeit/pkg/files/981880/view.zip)

**Comment by igorklopov** [comment]
@ydubois-fr You need to specify 'assets' directory as assets. For example, create package.json:
```
{
  "name": "views",
  "bin": "views.js",
  "pkg": {
    "assets": "assets"
  }
}
```
and then run `pkg package.json`

**Comment by ydubois-fr** [comment]
**@Igoklopov** PERFECT..... Thank you very much.....you solve my problem....everything works.....Thanks you. It's perfect.
**@firrae** Thank you for your help and the interest that you have brought to my problem. thanks a lot for your help

**Comment by goforward01** [comment]
Sorry for so late reply, Thanks @igorklopov @firrae @ydubois-fr, I'll try again later.
