### ISSUE TITLE
Keep cmd open after running .exe

### ISSUE THREAD

**Issue by vincenthawke** [zeit/pkg#644]
My .exe closes after finishing its work on windows 10. I would like it to stay open so that the user can read the text output. Is there a way to achieve this by modifying the main script JS file?

Temporarily solved it by wrapping .exe file in another .bat file, but hoped that there was a cleaner, 1-file solution

**Comment by Baskiney** [comment]
You can edit it in the code by including an iostream. Now you can atleast see the message.
```
const readline = `require('readline');

const rl = readline.createInterface({`
    input: process.stdin,
    output: process.stdout
});

console.log("Hello World!")
```

**Comment by vincenthawke** [comment]
> You can edit it in the code by including an iostream. Now you can atleast see the message.
> 
> ```
> const readline = require('readline')
> 
> const rl = readline.createInterface({
>     input: process.stdin,
>     output: process.stdout
> })
> 
> console.log("Hello World!")
> ```

That worked perfectly. Thanks!
