### ISSUE TITLE
Error: File or directory. Please recompile adding it as asset or script.

### ISSUE THREAD

**Issue by ganeshkbhat** [zeit/pkg#65]
A quick support - I am doing a test compile. Here is my package .json script I have added.

```
"pkg": {
    "scripts": "build/**/*.js",
    "assets": "views/**/*"
  }
```

Here is the folder structure

![folderstr](https://cloud.githubusercontent.com/assets/3424344/25708965/9ed71bea-3105-11e7-814f-d9395ee81292.png)

When I create a .exe it does create a exe but it gives an error saying this:

Error: File or directory 'C:\SGems\fullstack\5\views\index.html' was not included into executable at compilation stage. Please recompile adding it as asset or script.
    at error_ENOENT (evalmachine.<anonymous>:0:0)
    at findNativeAddonForStat (evalmachine.<anonymous>:0:0)
    at statFromSnapshot (evalmachine.<anonymous>:0:0)
    at Object.fs.stat (evalmachine.<anonymous>:0:0)
    at SendStream.sendFile (C:\snapshot\SGems\fullstack\5\node_modules\send\index.js:729:6)
    at SendStream.pipe (C:\snapshot\SGems\fullstack\5\node_modules\send\index.js:603:8)
    at sendfile (C:\snapshot\SGems\fullstack\5\node_modules\express\lib\response.js:1057:8)
    at ServerResponse.sendFile (C:\snapshot\SGems\fullstack\5\node_modules\express\lib\response.js:418:3)
    at evalmachine.<anonymous>:0:0
    at Layer.handle [as handle_request] (C:\snapshot\SGems\fullstack\5\node_modules\express\lib\router\layer.js:95:5)

Also, is there a way to keep the server running in quiet mode? Any options?

**Comment by igorklopov** [comment]
Please post your code.

**Comment by ganeshkbhat** [comment]
Here is the code. Simple express server:

```
var express = require('express');
var app = express();
var server = require('http').Server(app);
//var io = require('socket.io')(server);

server.listen(8888);

app.use('/lib', express.static('lib'));
app.use(function (req, res, next) {
    res.setHeader('Access-Control-Allow-Origin', 'http://localhost:8888');
    res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS, PUT, PATCH, DELETE');
    res.setHeader('Access-Control-Allow-Headers', 'X-Requested-With,content-type');
    res.setHeader('Access-Control-Allow-Credentials', false);
    next();
});
app.get('/', function (req, res) {
  res.sendFile(__dirname + '/views/index.html');
});


```

If I include socket.io it gives an error related to declaration of this.wsEngine and `require(this.wsEngine)` in the index.js does not resolve the issue. Is there an example of how I can include this?

**Comment by igorklopov** [comment]
I tried but failed to reproduce. Can you make a repo?

**Comment by ganeshkbhat** [comment]
[app.zip](https://github.com/zeit/pkg/files/978792/app.zip)

Please find files attached. Its a simple starter.

**Comment by igorklopov** [comment]
Seems the problem is that you run `pkg app.js`. Currently pkg does not know about package.json, because you specify `app.js` directly.

Instead you should add `app.js` as `bin` entry in package.json. And then run `pkg package.json` or simply `pkg .`.

**Comment by igorklopov** [comment]
I added your code as an example for pkg. Thanks!
Please look at https://github.com/zeit/pkg/blob/master/examples/express/index.js#L9
You should use __dirname explicitly for `serve-static` root.

**Comment by ganeshkbhat** [comment]
@igorklopov socket.io it gives an error related to declaration of this.wsEngine. How would I resolve that by explicit declarations? Any code examples?

**Comment by ganeshkbhat** [comment]
@igorklopov any help is welcome :-)

**Comment by Koka5** [comment]
i am also facing the same issue..  any solution ?


So what should i do?

What i have tried,

i just cloned the repo,, 
```
cd examples/express
npm install
node index.js //works great
pkg . 
./index-macos // does not work says views was not included in compilation stage
pkg package.json
./index-macos //  does not work..  again same issue
pkg index.js
./index-macos //  does not work..  again same issue
```

Please note, i have not changed a single character in the example.

last line of this [comment](https://github.com/zeit/pkg/issues/65#issuecomment-299594135) says "You should use __dirname explicitly for serve-static root."

at [line 9](https://github.com/zeit/pkg/blob/master/examples/express/index.js#L9) its written : 
"__dirname is used here along with package.json.pkg.assets"

now next one is more confusing..
as in the documentation last line of [section](https://github.com/zeit/pkg#detecting-assets-in-source-code) says that "This way you may even avoid creating pkg config for your project."

So even when the assets is included, nothing works..

May i am doing some silly mistake, please help me out.

**Comment by Judgemenot** [comment]
T grotto

**Comment by Koka5** [comment]
it was a silly mistake.. Just forget it.. it got it working..

**Comment by uullrich** [comment]
Could you please tell me the reason / solution from your mistake?

**Comment by Koka5** [comment]
@uullrich  in the package.json i had not mentioned the "bin" property

**Comment by essivision** [comment]
I have same problem and solve it
```
"bin":"./index.js",
  "pkg": {
    "assets": "./node_modules/figlet/fonts/Standard.flf"
  }
```
and after that run:
```
pkg package.json
```
finally create another `.exe` file with directory name

**Comment by nathanmfast** [comment]
@essivision Thanks! That's exactly what I needed.
