### ISSUE TITLE
How to support es6 "class" syntax？

### ISSUE THREAD

**Issue by Dr-Harris** [zeit/pkg#655]
I use ES6 class syntax in my `koa-2` app.
when i package my app, there are the error msg:
`This experimental syntax requires enabling the parser plugin: 'classProperties'`
I try to add `@babel/plugin-proposal-class-properties` in my app and .babelrc ,but it doesn't work.

**Comment by Dr-Harris** [comment]
.babelrc looks like:
```
{
  "presets": ["es2015", "stage-0"],
  "plugins": [["@babel/plugin-proposal-class-properties", { "loose": true }], "transform-runtime"]
}

```

**Comment by d1soft** [comment]
@Dr-Harris hello, you resolved it?

**Comment by Dr-Harris** [comment]
> @Dr-Harris hello, you resolved it?

No...  :(

**Comment by d1soft** [comment]
@Dr-Harris, I resolved it with installing babel-node and transpiling sources. After that i without problems builded executable files. If you need more explanations, I can mention me here.

**Comment by Dr-Harris** [comment]
> @Dr-Harris, I resolved it with installing babel-node and transpiling sources. After that i without problems builded executable files from **builded by babel (babel -b) sources**. If you need more explanations, you can mention me here.

thank you..I'll try it.

**Comment by RudyMaringer** [comment]
@d1soft Hi, Could you please give more details ?
