### ISSUE TITLE
'pkg' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by psaxena** [zeit/pkg#660]
Hi,

I installed pkg module on my windows and did not notice any issue while installing. My package json is updated with pkg version "pkg": "^4.3.7". But when I run pkg -v or pkg. I get error:

'pkg' is not recognized as an internal or external command

I've tried installing pkg globally and with admin console as well but same output.

Also, interestingly, when I run nodejs command prompt pkg --help does not give error. Not sure what is changed between normal windows console and nodejs command prompt wrt to pkg.

Any idea what could be causing this how to solve?

Thanks,
Pooja

**Comment by psaxena** [comment]
Solved by running "c:\Program Files\nodejs\nodevars.bat"

**Comment by Afranzio** [comment]
> Solved by running "c:\Program Files\nodejs\nodevars.bat"

Beaba Your Veraa Level 💕💕💕

**Comment by tarkungZZ** [comment]
> Solved by running "c:\Program Files\nodejs\nodevars.bat"

Not working for me.
