### ISSUE TITLE
Get filename

### ISSUE THREAD

**Issue by Innomalist** [zeit/pkg#662]
Hi,
How can i get the filename for the app because __filename returns emulated path (/snapshot/.....) not the real path executable is on it.

Thanks in Advance,

**Comment by Innomalist** [comment]
Found it sorry :)

**Comment by bogdan-calapod** [comment]
@Innomalist how/where did you find this ? The documentation is a bit lacking on this one 😕

**Comment by bogdan-calapod** [comment]
For anyone looking for a solution for this, the first argument from `process.argv` gives the complete path to your executable, including the filename.

**Comment by innomal** [comment]
@bogdan-calapod Under "Snapshot filesystem" in `README.md` you can find how to do so.
