### ISSUE TITLE
Why can't i include minor version of node js

### ISSUE THREAD

**Issue by tbhaxor** [zeit/pkg#669]
On the command `$ pkg app.js -t node10-linux-x86` why does it pick `v10.4.1` ?

**Comment by DaneTheory** [comment]
Under the hood, `pkg` relies on `pkg-fetch` in handling what version of NodeJS to use. Check the repo for more info: https://github.com/zeit/pkg-fetch

**Comment by tbhaxor** [comment]
So it means i should rely on what pkg is fetching...
What if the minor version pkg is fetching is vulnerable ?

**Comment by DaneTheory** [comment]
@tbhaxor nothing can be done about it. `pkg` doesn't download NodeJS binary versions from NodeJS.org
Zeit is providing their own Node versions via `pkg-fetch`. I'm not sure as to why exactly. I've asked the other contributors about this exact thing. Haven't received an answer yet.
