### ISSUE TITLE
Error! connect ETIMEDOUT 54.231.33.195:443

### ISSUE THREAD

**Issue by arden** [zeit/pkg#67]
[root@iZ94hmrh5tzZ ra-broker]# pkg index.js
> Targets not specified. Assuming:
  node7-linux-x64, node7-macos-x64, node7-win-x64
> Fetching base Node.js binaries to: ~/.pkg-cache
  fetched-v7.6.0-linux-x64     [====================] 100%
> Error! connect ETIMEDOUT 54.231.33.195:443
> Asset 'v1.9/uploaded-v1.9-node-v7.6.0-linux-x64' not found by direct link
  fetched-v7.6.0-linux-x64     [====================] 100%
> Error! connect ETIMEDOUT 54.231.33.195:443

**Comment by raphaelsoul** [comment]
got some problem. This IP is located to AWS, so, it is problem caused by GFW.......

**Comment by raphaelsoul** [comment]
currently I do like this:
compile a js file on a machine, which not located in China Mainland. and you will have some files at  `~/.pkg-cache`. Download it and put it in your local develop environment. It's done.

this files are node executable. 
![tim 20170512094906](https://cloud.githubusercontent.com/assets/8615787/25979088/ea305522-36f8-11e7-8f7d-cbfc238789d1.png)

These files are all node executable. You can do like this: 
![tim 20170512095451](https://cloud.githubusercontent.com/assets/8615787/25979144/32b2f43a-36f9-11e7-9993-97d9773c9155.png)

I guess you can directly rename and copy the target node executable to `~/${username}/pkg-cache/v1.9`


![tim 20170512095747](https://cloud.githubusercontent.com/assets/8615787/25979192/99655c18-36f9-11e7-8c8d-64b612f5bbc4.png)
`. Good luck

**Comment by igorklopov** [comment]
Reopened in pkg-fetch

**Comment by chengsu** [comment]
where can I download the prebuild executable?
