### ISSUE TITLE
socket.io 404  in nestjs

### ISSUE THREAD

**Issue by GuanglongDu** [zeit/pkg#689]
Hello
i build https://github.com/nestjs/nest/tree/master/sample/02-gateways in pkg, i connected socket.io throws 404 error in html , but it could connected when npm  start in command , how could i resolve this?

Thanks.

**Comment by DanStory** [comment]
I resolved this same issue by adding the `@nestjs/websockets` module folder to pkg's assets via `package.json`.
```json
"pkg": {
    "assets": [
      "node_modules/@nestjs/websockets/**/*"
    ]
  }
```

**Comment by nickhaughton** [comment]
I am having the same issue, the above fix doesn't work for me

**Comment by GuanglongDu** [comment]
@DanStory It works, Thanks.

**Comment by pascalbayer** [comment]
@GuanglongDu How did you fix that issue in your case? Doesn't work for me if I simply put the `assets` statement in the `package.json`

**Comment by db2crush** [comment]
@DanStory Thanks. You saved me.
