### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by nojaf** [zeit/pkg#71]
Hi sorry for asking this, I just want to double check before I get all excited.
So I have a node 6.x app running in production and my app was the sole reason my custom had to install node in the first place. 

Could I uninstall node 6 on the server, develop the next iteration in say node 7 and pkg it to an executable express server? Would that actually work?

**Comment by jgoux** [comment]
I just did it with a node.js 6 application ported to node.js 7.

It works beautifully! 👍 

As the node.js engine is packaged within your app, you have 0 dependencies outside of the app binary. ⭐️

**Comment by nojaf** [comment]
This is huge, thanks for the quick response!
