### ISSUE TITLE
fails to pkg node-available esnext syntax (e.g. private class fields)

### ISSUE THREAD

**Issue by panva** [zeit/pkg#719]
Hi, the following is valid syntax (using esnext private class fields) supported by node 12. And `pkg` fails to pack it.

```js
class Person {
  #name
  constructor(name) {
    this.#name = name
  }

  greet() {
    console.log(`Hi, my name is ${this.#name}`);
  }
}

new Person('@panva').greet();
```

```sh
❯ node -v
v12.0.0

❯ node index.js
Hi, my name is @panva

❯ pkg index.js -d
> pkg@4.4.0
> Targets not specified. Assuming:
  node12-linux-x64, node12-macos-x64, node12-win-x64
> [debug] Bytecode of %1 is added to queue
  /Users/panva/repo/pkgex/index.js
> [debug] Stat info of %1 is added to queue
  /Users/panva/repo/pkgex/index.js
> Error! Unexpected character '#' (2:2)
  /Users/panva/repo/pkgex/index.js
```

I believe that whatever parser `pkg` uses to parse the code and its dependencies should reflect the available node syntax so that transpiling is not required for this new syntax to be packageable. This syntax is starting to show up in new modules and transpiling deps is just not what everyone should be forced to do.

WDYT?

**Comment by rse** [comment]
Please act on this: there are popular mainstream modules like HAPI which use private fields, because they simply require Node 12. But one cannot package applications depending on those modules without transpiling, although `pkg` provides Node 12 itself.

**Comment by FGRibreau** [comment]
[Found the issue](https://github.com/zeit/pkg/pull/891/files), opened a PR: #891 :)

**Comment by igorklopov** [comment]
Thanks!
