### ISSUE TITLE
[question] How packed app load external resource

### ISSUE THREAD

**Issue by RyanBram** [zeit/pkg#730]
When I read the manual about packaging an application, there was written if the resource directory should be written explicitly and all of the resources will be embedded into packaged application.
I use pkg for game which has many resource and embedding all of the resource seems not an ideal solution, because I can use Enigma Virtual Box for similar purpose.

My question:
Can I use pkg, only to pack the main.js into node.js, but the other resources or scripts are stay in their directory structure without being embedded inside node.js?

**Comment by marksink** [comment]
You can access files outside of your packaged app with process.cwd().  Like So:

const yourNonPackagedFile = process.cwd() + '/notInPackage.txt';

**Comment by RyanBram** [comment]
Thank you very much for your answer.
