### ISSUE TITLE
How to run packaged EXE with hidden command prompt

### ISSUE THREAD

**Issue by psaxena** [zeit/pkg#742]
Hi,

I am bale to package node application and can run exe by opening command prompt and running exe.

I want to run this node app(as an exe) silently in windows i.e. command prompt should not be visible. Any idea how to achieve this?

Thanks,
Pooja

**Comment by dd-pardal** [comment]
This is not specific to pkg nor nodejs, I think. There are various programs made for that.

**Comment by rao123dk** [comment]
> Hi,
> 
> I am bale to package node application and can run exe by opening command prompt and running exe.
> 
> I want to run this node app(as an exe) silently in windows i.e. command prompt should not be visible. Any idea how to achieve this?
> 
> Thanks,
> Pooja

Hi, @psaxena @dd-pardal I have built executable file for all 3 platforms. Its works fine on Linux and macOS, but it doesn't run on windows. can you please help me with this?  

Is there any specific way to run on windows?


NodeJS:- v10.16.2
Pkg :- v4.4.0
Platform :- Linux

**Comment by rao123dk** [comment]
> Hi,
> 
> I am bale to package node application and can run exe by opening command prompt and running exe.
> 
> I want to run this node app(as an exe) silently in windows i.e. command prompt should not be visible. Any idea how to achieve this?
> 
> Thanks,
> Pooja

@psaxena you can write a shell script for this.

**Comment by rao123dk** [comment]
Hi, @psaxena @dd-pardal I have built executable file for all 3 platforms. Its works fine on Linux and macOS, but it doesn't run on windows. can you please help me with this?

Is there any specific way to run on windows?

NodeJS:- v10.16.2
Pkg :- v4.4.0
Platform :- Linux

**Comment by psaxena** [comment]
Got this working with powershell script.

**Comment by psaxena** [comment]
> Hi, @psaxena @dd-pardal I have built executable file for all 3 platforms. Its works fine on Linux and macOS, but it doesn't run on windows. can you please help me with this?
> 
> Is there any specific way to run on windows?
> 
> NodeJS:- v10.16.2
> Pkg :- v4.4.0
> Platform :- Linux

I was able to run by typing exe name on command prompt. You may check if you've any logs for failure

**Comment by rao123dk** [comment]
I also found. It was node.js version issue.

**Comment by YD1722** [comment]
> I also found. It was node.js version issue.

Can you be more specific? Which versions is do support and which versions doesn't

**Comment by rao123dk** [comment]
"pkg": "4.3.7" support with node-10. I was using node10 with Pkg :- v4.4.0 so I was not compatible.
