### ISSUE TITLE
"TypeError: n is undefined" in browser when packaging Express app serving a create-react-app build

### ISSUE THREAD

**Issue by danielamiir** [zeit/pkg#783]
I have an NodeJS with Express application that servs a Create-React-App production build. When starting the application with `npm start` in production all the pages are working fine. The packaging process works fine but when running the mac-executable all the pages except the last one are working as they should. On the last page I am getting a `TypeError: n is undefined` in the browser console (Firefox). I am running my packaging by calling `pkg .` on MacOS.

In my package.json I have tried several different alternatives:

Alternative 1:

    "pkg": {
        "scripts": [
          "client/build/*.js",
          "client/build/static/js/*.js"
        ],
        "assets": [
          "client/build/favicon.ico",
          "client/build/manifest.json",
          "client/build/index.html",
          "client/build/robots.txt",
          "client/build/data/*",
          "client/build/asset-manifest.json",
          "client/build/static/css/*",
          "client/build/static/js/*.map"
        ]
    }

Alternative 2:

    "pkg": {
        "assets": [
          "client/build/favicon.ico",
          "client/build/manifest.json",
          "client/build/index.html",
          "client/build/robots.txt",
          "client/build/data/*",
          "client/build/asset-manifest.json",
          "client/build/*.js",
          "client/build/static/css/*",
          "client/build/static/js/*"
        ]
    }

Alternative 3:

    "pkg": {
        "assets": [
          "client/build/**/*"
        ]
    }

They all raise the same issue. 

client/build/data folder contains .csv and .txt files.

I appreciate all help.

**Comment by danielamiir** [comment]
Managed to solve it by listing all files explicitly in the data folder.

**Comment by ronnaf** [comment]
hi @danielamiir! i'm trying to package a create-react-app typescript project. can you share what config you ended up using? thank you!
