### ISSUE TITLE
Armv6 binary for node10

### ISSUE THREAD

**Issue by Muzzamil1** [zeit/pkg#784]
Hi!
I am using 
node version == v10.16.0
pkg version == 4.4.0
Raspberry pi zero w ==  Linux_armv6
It just hangs at the `make `

![Error in Pi zero](https://user-images.githubusercontent.com/53085438/67007289-7e229380-f100-11e9-8762-113e132b1eb5.png)

This is because there are no binaries for armv6 at https://github.com/zeit/pkg-fetch/releases
After many hours make still did not progress.
Is there any way I can use the NodeJS that is already installed?

**Comment by icebob** [comment]
I've built it (it takes ~ 10 hours). Unzip and put it into the PKG_CACHE_PATH
[built-v10.15.zip](https://github.com/zeit/pkg/files/3939179/built-v10.15.zip)

**Comment by Muzzamil1** [comment]
Thanks.

**Comment by asorg74** [comment]
> I've built it (it takes ~ 10 hours). Unzip and put it into the PKG_CACHE_PATH
> [built-v10.15.zip](https://github.com/zeit/pkg/files/3939179/built-v10.15.zip)

hi icebob

Firstly, thank you very much for the nodejs10 binary.  I've tried to build it with my Raspberry Zero W, and after 12 hours, I just give up.  It simply too long.

I've extract build-v10.15.zip into .pkg-cache/v2.6, rename it to fetched-v10.15.3-linux-armv6  but upon building the exe file, pkg keeps on looking for fetched-v10.17.0-linux-armv6 ( which it will try to compile again ).

how do I force pkg to use the binary that you give here ?
I've tried to google it, read the pkg home page, and couldn't find it.

thank you very much in advance

**Comment by icebob** [comment]
I think you can't force it. And it means they updated the supported Node 10 version from 10.15 to 10.17.
If you think, I can give advice about how I compiled it with Docker & QEmu.

**Comment by asorg74** [comment]
> I think you can't force it. And it means they updated the supported Node 10 version from 10.15 to 10.17.
> If you think, I can give advice about how I compiled it with Docker & QEmu.

hi icebob

thank you for your quick reply.

yes please, how do you compile it with Docer & QEmu ?
Is it the same like https://github.com/robertsLando/pkg-binaries  ?

**Comment by icebob** [comment]
Yeah, maybe. I didn't know this repo, try it. If not work I will create an example

**Comment by asorg74** [comment]
I've tried it a few days ago.

The Using Docker step was stopped at last step ./build.sh
LinuxMint says standard_init_linux.go:211 exec user process caused "exec format error"

The Manually step, was the one I that I tried and stopped compiling after more than 12 hours and still not yet finished.  I wonder if there is a quicker way.  Otherwise I may try to recompile again in the future. Maybe I'll just wait until it finished.

thank you so much

**Comment by icebob** [comment]
If you got "exec format error", you should exec this `sudo docker run --rm --privileged multiarch/qemu-user-static:register`

By the way, QEmu is an emulator and it can very slow. For me on a server machine, the v10.15 takes ~ 10 hours to generate. So maybe you should wait more than 12 hours :(

**Comment by asorg74** [comment]
hi icebob

sorry for the late reply.

I've tried to compile it for about 20 hours and still not yet finished.
So I just ended up porting the small project to Golang which is very easy to build for armv6.

I will try what you suggest later when time is good for me.

thank you :)
