### ISSUE TITLE
[QUESTION] Trying to exect cmd command on snapshot folder

### ISSUE THREAD

**Issue by xXLokerXx** [zeit/pkg#803]
I try to use `child_process` library to exect a command from `sequelize`, but the command is executed in the main folder where i have the pkg executable file, theres a way to do this executed on snapshot folder where on `exe` file (windows example)?

**Comment by igorklopov** [comment]
You need to write it to real file system first (copy from snapshot to real, for example, based on `process.execPath`), and then execute.

**Comment by xXLokerXx** [comment]
@igorklopov i have the next code:
```
ncp(join(__dirname, '../node_modules'), join(process.cwd(), '/node_modules'), function (err) {
		if (err) {
			return console.error(err);
		}
		const cmd = `${process.cwd()}/node_modules/.bin/sequelize db:migrate --migrations-path "${migrationPath}" --url ${url}`

		exec(cmd, (error, stdout, stderr) => {
			console.log("error: ", error)
			console.log("========================")
			console.log("stdout: ", stdout)
		})
		console.log('done!');
	});
```

i try to copy the node_modules folder, but the copy does not have the `.bin` folder where is supoused to execute the command, do you have any example that maybe help me?

**Comment by xXLokerXx** [comment]
I couldn't use ncp for my problem
