### ISSUE TITLE
Error! Cannot read file, ENOENT worker_threads

### ISSUE THREAD

**Issue by glenndehaan** [zeit/pkg#807]
After updating pkg from version 4.4.0 to 4.4.1 I got the following message:
![Schermafbeelding 2019-12-10 om 14 35 52](https://user-images.githubusercontent.com/7496187/70533967-6bee3000-1b5a-11ea-938a-33cd1836efc3.png)

Downgrading back to 4.4.0 fixes this. I'm running MacOS 10.13.6, NodeJS v8.12.0.
Am I missing something? This is happening in multiple projects that used to work fine.

**Comment by igorklopov** [comment]
Does it work this way even if the project is simply `console.log(42)`? Can you please also narrow down to a smallest code snippet?

**Comment by glenndehaan** [comment]
@igorklopov That produces the same error:
<img width="992" alt="Schermafbeelding 2019-12-10 om 21 10 53" src="https://user-images.githubusercontent.com/7496187/70565051-96a7ab00-1b91-11ea-8bf3-14c0f754f57f.png">

**Comment by glenndehaan** [comment]
Just to show the output of version 4.4.0:
<img width="1052" alt="Schermafbeelding 2019-12-10 om 21 12 31" src="https://user-images.githubusercontent.com/7496187/70565179-d53d6580-1b91-11ea-9f59-ecc6fb061bfa.png">

**Comment by Nihiue** [comment]
Package **write-file-atomic** causes this problem.

![image](https://user-images.githubusercontent.com/5763301/70767449-55cfb200-1d9c-11ea-9662-b65d32c4475d.png)

[write-file-atomic-npm](https://www.npmjs.com/package/write-file-atomic )
