### ISSUE TITLE
Does not require modules properly with version 4.4.1

### ISSUE THREAD

**Issue by travist** [zeit/pkg#808]
We ran into some problems with the latest 4.4.1 release where some modules are not getting "required" properly. The module we were having a problem with was ```azure-storage```.  Pretty sure this would show the problem.

```
const storage = require('azure-storage');
console.log('This should print something!!!');
```

In 4.4.0 this would work just fine, but in 4.4.1 the code never gets to the console.log.

**Comment by igorklopov** [comment]
Thanks! What is `--target` option specified in cli? What is the command line generally?

**Comment by travist** [comment]
We use it in a Dockerfile build script whose base image is node10-alpine. So Alpine Linux would be the target.

**Comment by travist** [comment]
I just found the exact target in the package.json.  It is node10-alpine-x64 but it is also an issue with node12-alpine-x64

**Comment by sharathbaddam** [comment]
Replicated same issue on Windows 10, node 12 with pkg 4.4.2
Packages like 'azure-storage' have separate packages inside a package. So the require statement here => _https://github.com/Azure/azure-storage-node/blob/master/lib/common/util/util.js#L22_ is requiring 'md5-wrapper' which is in a different folder but as a separate package => _https://github.com/Azure/azure-storage-node/tree/master/lib/common/md5-wrapper_

**Comment by igorklopov** [comment]
Please try again with `pkg@4.4.4`
