### ISSUE TITLE
Error not found uploaded-v2.6-node-v10.17.0-linux-armv7

### ISSUE THREAD

**Issue by Ks89** [zeit/pkg#810]
HI!
I'm using an arm v7 device, but it throws an error, because this file https://github.com/zeit/pkg-fetch/releases/download/v2.6/uploaded-v2.6-node-v10.17.0-linux-armv7 is missing

**Comment by wuguzaliang** [comment]
First install node v10.15.3 via downloading package from node official site.   
 Try to run pkg -t node10.15.3-linux-armv7 .
    It will work.
    Hope help you.

**Comment by wuguzaliang** [comment]
![1](https://user-images.githubusercontent.com/17598406/70961914-48793700-20be-11ea-9846-30a2224c98e8.jpg)
It only support these several existed version

**Comment by wuguzaliang** [comment]
![1](https://user-images.githubusercontent.com/17598406/70962017-98f09480-20be-11ea-8aaf-f84c9745fb23.jpg)

**Comment by Ks89** [comment]
I fixed this issue forcing this in my package.json

```
"targets": [
   "node10.15.3"
]
```

This will download the right file.

**Comment by Ks89** [comment]
> ![1](https://user-images.githubusercontent.com/17598406/70962087-d3f2c800-20be-11ea-836c-89fdc6a356d9.jpg)
> 
> It only support these several existed version

yes, this file uploaded-v2.6-node-v10.17.0-linux-armv7 is missing and if you don't force the target to a specific version you'll receive this error
