### ISSUE TITLE
How to access filesystem's /snapshot directory? (not bundled assets)

### ISSUE THREAD

**Issue by cspotcode** [zeit/pkg#84]
If I use pkg to make a CLI tool that manipulates files, then it's possible that users might try to use it on a `/snapshot` directory on their filesystem.  (rare but possible, and for a CLI tool, I'd need to cover all cases)  How do I read and write to the host filesystem's `/snapshot` directory with a `pkg`-bundled executable?  I couldn't find this in the documentation, but maybe I missed the section that explains this.

Example:

```
cd /snapshot
vim index.js
my-pkg-bundled-utility uploadFileToWebsite index.js
```

**Comment by igorklopov** [comment]
It is not possible to access `/snapshot` on real file system. All calls that have `/snapshot` in path are redirected into inside executable.

**Comment by d-01** [comment]
I'd like to share a temporary solution for Windows:

```
fs.readdirSync('C:\\snapshot');        // to access "virtual" pkg directory
fs.readdirSync('\\\\.\\C:\\snapshot'); // to access real "C:\snapshot" directory
```

Possible cross-platform solution is to parse dir/ls console commands output.
PS: Feels weird that such a great convenient tool has such a nonsense limitation.
