### ISSUE TITLE
private: true is defined in package.json but still exposes code

### ISSUE THREAD

**Issue by sitesgithub** [zeit/pkg#841]
How can I fix this?

**Comment by sergiz** [comment]
Do you refer to your scripts using path.join(..)? Then auto asset detection will kick in, and they will be included as assents, not scripts.

**Comment by sitesgithub** [comment]
I don't, its just 1 file with 2 assets in a glob but the 1 file is displayed if i look in a hex editor.

**Comment by sergiz** [comment]
Did you try compiling with --debug and then checking the log?

**Comment by sitesgithub** [comment]
I have not, I will try to

**Comment by sergiz** [comment]
--debug won't make a difference, the purpose is to long at the output and see what does it say ...

**Comment by sitesgithub** [comment]
It says some things that are disclosed code, but still shows the source (and it says that for my dependencies

**Comment by sitesgithub** [comment]
CLOSED: i am a dumb person and did not run the arg --public with it
