### ISSUE TITLE
Why does it include devDependencies?

### ISSUE THREAD

**Issue by sergiz** [zeit/pkg#844]
I run a simple example:

```
// pkg.js
const yamp = require('node-yaml');
```

with the following command
`pkg pkg.js --debug`

Pkg then includes all possible devDependencies of node-yaml and its own dependencies (including eslint, babel and other stuff). I would expect it to only include the code that it actually needs for this executable?

**Comment by gigouni** [comment]
Can you prune your dependencies before running `pkg`?

With node/npm, you could do

```
npm install --production && pkg pkg.js --debug
```

or

```
npm install && <your-build-commands> && npm prune --production && pkg pkg.js --debug
```

Assuming you've not installed `pkg` in your `devDependencies` (dependencies or globally through CI by example)

**Comment by sergiz** [comment]
Thanks for you input. I discovered that the version of node-yaml I was using was causing the problem (the latest version seems to work fine).
