### ISSUE TITLE
pkg errors with "No available node version satisfies 'node5'"

### ISSUE THREAD

**Issue by boughtonp** [zeit/pkg#85]
Running `pkg .` with a package.json containing no target (i.e. expecting default/current version):
```
  ,"pkg":{"scripts":"engine/**/*.js","assets":"engine/**/*"}
  ,"bin":"engine/app.js"
```
Returns `Error! No available node version satisfies 'node5'`

Trying with different targets specified such as "node5.0" or "node5-win" or "v5.0.0" or "latest-v5.x" or returns the following:
> Error! No available node version satisfies 'node5.0'
> Error! No available node version satisfies 'node5'
> Error! Unknown token 'v5.0.0' in 'v5.0.0'
> Error! Unknown token 'v5.x' in 'latest-v5.x'

I'm pretty sure there was a version of Node 5 downloaded when installing pkg, but I can't find where it was placed and there doesn't appear to be a command to list available Node versions / valid targets?

**Comment by igorklopov** [comment]
`pkg` supports only versions supported by Node.js itself. `io.js` and `node5` are out of that list. Is it acceptable for you to specify `--targets node6` in your compilation command line? Btw, you can also add `targets` entry to package.json.pkg (along with `scripts` and `assets`).
