### ISSUE TITLE
require some modules cannot resolve '

### ISSUE THREAD

**Issue by hnlinzhi19** [zeit/pkg#86]
when i require 'browser-sync' ,so i run pkg just show some problem:

`Warning Cannot resolve 'this.wsEngine'
  /Users/linz/Documents/linz/lin_learn/mobx-learn/node_modules/engine.io/lib/server.js
  Use a string literal as argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.`

my code  just to test 

`
var nowDir = path.parse(process.title).dir;
var bs = require("browser-sync").create();

// Start a Browsersync static file server
bs.init({
    server: nowDir
});`

**Comment by igorklopov** [comment]
Please upgrade to `pkg@3.0.4` and try again
