### ISSUE TITLE
Error! Escape sequence in keyword delete (76:11)

### ISSUE THREAD

**Issue by simon-czychy** [zeit/pkg#94]
Hey, im trying to use pkg.

When I run pkg app.js i get this Messages:

`Targets not specified. Assuming:
  node6-linux-x64, node6-macos-x64, node6-win-x64
> Fetching base Node.js binaries to: ~/.pkg-cache
  fetched-v6.10.0-linux-x64    [====================] 100%
  fetched-v6.10.0-win-x64      [====================] 100%
  fetched-v6.10.0-macos-x64    [====================] 100%
> Warning Cannot resolve 'bindingsPath'
  C:\Users\simon\git\b2b-addon-installer\node_modules\appjs\lib\bindings.js
  Use a string literal as argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
> Warning Cannot resolve 'bindingsPath'
  C:\Users\simon\git\b2b-addon-installer\node_modules\appjs\lib\bindings.js
  Use a string literal as argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
> Error! Escape sequence in keyword delete (76:11)
  C:\Users\simon\git\b2b-addon-installer\node_modules\appjs\lib\handlers.js`

No executables were created. I tried googling but didnt find anything i could understand.
Im running Windows 10. I tried "pkg app.js" from windows cmd and from ubuntu bash on windows.

Could you give me a hint how to fix this??

Greetings

Simon

**Comment by igorklopov** [comment]
Try running the project in original node. Or even you can try `node handlers.js` just against that single file. You will get syntax error from `node`. Pkg can compile only files with correct syntax.
