### ISSUE TITLE
how to specify target with full version of node 

### ISSUE THREAD

**Issue by zhaifly** [zeit/pkg#95]
i use --targets node0-linux-x64, it will fetch 0.12.25 but i want to use 0.10.38!
someone can help with such scenario!
very thanks

**Comment by simast** [comment]
0.10 is not supported by pkg. See [this file](https://github.com/zeit/pkg-fetch/blob/master/patches/patches.json) for a list of supported node versions.

**Comment by zhaifly** [comment]
thanks very much！

BR.
-zhaifly

**Comment by igorklopov** [comment]
Thanks @simast!
