### ISSUE TITLE
How to omit the directory in the builds

### ISSUE THREAD

**Issue by codeofnode** [zeit/pkg#97]
Consider following code, which is going to be pkg'ed

say i was working in "/Users/me/box/project"

```
var http = require('http');
http.createServer(function (req, res) {
   throw new Error('Check the stack trace... It says the name of user and path from where the pkg was done');
  // here in the stack trace i can see this path "/snapshot/Users/me/box/project"
}).listen(3001);
```

I do not want to disclose my username or working path into shipped file at all.

I want the stack trace as "/snapshot" that is to omit "/snapshot/Users/me/box/project" everywhere inside shipped pkg'ed file.

**Comment by igorklopov** [comment]
To be solved by pkg@3.1

**Comment by codeofnode** [comment]
Can i get some hints so that i can do that at my own.. and probably i will be able sent pr on this.

**Comment by nicohaenggi** [comment]
@codeofnode if you are looking for a quick "fix" without changing the codebase, you can just work in your main directory of your system disk. not really convenient, but could be used as a workaround  if it's an emergency.

**Comment by igorklopov** [comment]
@nicohaenggi That's true 👍

**Comment by codeofnode** [comment]
Please add any documentation for this configuration (to omit path)?
