### ISSUE TITLE
"Cannot resolve..." with node-ninja, node-gyp and mocha

### ISSUE THREAD

**Issue by gillez** [zeit/pkg#98]
Hi,

I am trying to compile an application that uses couchbase, and other modules, which in turn use node-ninja, node-gyp and mocha.  I get warnings from all three of these similar to the following:

```
Warning Cannot resolve ''./' + c' 
  node_modules/node-gyp/lib/node-ninja.js
  Use a string literal as argument for 'require', or leave it as is and specify the resolved file name in 'scripts' option.
```

Looking at the node-ninja code, this comes from the following segment:

```
 commands.map(function (c) {
    return '    - ' + c + ' - ' + require('./' + c).usage
 })
```

I've read the "Assets" and "Scripts" sections of the pkg Readme but I'm still confused about how to resolve this.  Do I need to find out every script that may possibly be in the "commands" array (used in the segment about) and specify each of these in "assets"?  Has anyone else tried compiling an app that uses one of these libraries?

Thanks,
Giles

**Comment by igorklopov** [comment]
Ok. Aside that warnings does the compiled application work well? Or has any run time issues?

**Comment by gillez** [comment]
Thanks for the reply.  At the moment, I haven't reached the point where I have a complete executable so I can't answer this yet.  My node server does run but I'm not yet including my website files as assets so get an ENOENT error when navigating.  

I just wanted to check whether there was a standard solution to the node-ninja issue whilst I was trying to get the rest of the app working.  I'll update when I have fixed the website assets and updated all paths, then I'll know more.

**Comment by gillez** [comment]
Hi @igorklopov,

I have now packaged all relevant files and everything seems to work as expected!  My compiled output consists of only four files - the executable and three .node files (which, as I understand it, can't be enclosed in the package at the moment).  The original server directory contains several hundred files so this really is awesome!

I still get the warnings from node-ninja, node_gyp and mocha, but so far it appears I can ignore them as I haven't seen any runtime issues.

Thanks for the good work on pkg.

Giles

**Comment by igorklopov** [comment]
@gillez Hi! I am very glad! I constantly make `pkg` suppress warnings from packages that are known to work well (along with compatibility tests https://github.com/zeit/pkg/tree/master/test/test-79-npm). So, probably you will not see those warnings in future releases.

**Comment by gillez** [comment]
Thanks for your help Igor.

I've got a separate issue now related to cross-platform building but I will create a separate ticket for that.

**Comment by gillez** [comment]
Closing this issue as I am happy with Igor's answer.
