### ISSUE TITLE
Dependency issue : no such package available : @types/fs-extra

### ISSUE THREAD

**Issue by WoodySlum** [zeit/pkg#99]
Hello, I meet a dependency issue when using `npm install`:

    npm ERR! code E404
    npm ERR! 404 no such package available : @types/fs-extra
    npm ERR! 404
    npm ERR! 404  '@types/fs-extra' is not in the npm registry.
    npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
    npm ERR! 404 It was specified as a dependency of 'fs-promise'
    npm ERR! 404
    npm ERR! 404 Note that you can also install from a
    npm ERR! 404 tarball, folder, http url, or git url.

**Comment by igorklopov** [comment]
https://www.npmjs.com/package/@types/fs-extra
Please check your internet connection. Also probably something wrong with your npm proxy.
Btw, are you installing from master branch?

**Comment by WoodySlum** [comment]
I'm using Sinopia as npm proxy (and personal repo).
Removing the proxu from .npmrc file seems to work.
Not perfect, but it should work now.
